### ISSUE TITLE
Footer - Continuous deployment rule is archived

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People#206]
(Reported by @adamcogan)

Footer links to an archived continuous deployment rule:
![image](https://user-images.githubusercontent.com/600044/86546780-cbd67900-bf79-11ea-959e-f28b443ab270.png)
**Figure: Footer has a link for continuous deployment**

![image](https://user-images.githubusercontent.com/600044/86546785-d133c380-bf79-11ea-9997-3b193a123012.png)
**Figure: Rule has been archived**

- [ ] Change link to point to a current rule about continuous deployment

**Comment by SebastienBoissiere** [comment]
Created [PBI 54651](https://dev.azure.com/ssw/SSW.People/_workitems/edit/54651/)

**Comment by JackDevAU** [comment]
Closing as this has been fixed. The rule is no longer archived!
