### ISSUE TITLE
Footer - GitHub should link to rules to better GitHub

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People#207]
(reported by @adamcogan)

![image](https://user-images.githubusercontent.com/600044/86547142-4fdd3080-bf7b-11ea-911d-3d5432c64289.png)
**Figure: GitHub link in the footer goes to a static site rule instead of rules _about_ GitHub

- [ ] Github should link to https://rules.ssw.com.au/rules-to-better-github

**Comment by SebastienBoissiere** [comment]
Added to [PBI 54467](https://dev.azure.com/ssw/SSW.People/_workitems/edit/54467/)

**Comment by SebastienBoissiere** [comment]
Hi @wicksipedia 
CC @adamcogan 

This closes #207.

The link on 'GitHub' now links to https://rules.ssw.com.au/rules-to-better-github
![image](https://user-images.githubusercontent.com/28290353/87627195-82540e00-c771-11ea-8445-b3cdfc357148.png)
**Figure: The GitHub link had been changed to 'Rules to better Github'**
