### ISSUE TITLE
Footer - Missing Facebook link

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People#208]
(reported by @adamcogan)

In the footer, the Facebook link does not link to anything

![image](https://user-images.githubusercontent.com/600044/86547322-f0cbeb80-bf7b-11ea-94b0-b14797182d25.png)
**Figure: Facebook link has no href**

- [ ] Facebook link should go to https://www.facebook.com/SSW.page/

**Comment by SebastienBoissiere** [comment]
Added to [PBI 54467](https://dev.azure.com/ssw/SSW.People/_workitems/edit/54467/)

**Comment by SebastienBoissiere** [comment]
Hi @wicksipedia 
CC @adamcogan 

This closes #208.

The facebook link in the footer has been fixed and link to SSW Facebook page.

![image](https://user-images.githubusercontent.com/28290353/87626725-7451bd80-c770-11ea-81a5-a5b082c9b9bf.png)
**Figure: The link now appears correctly when hovering the Facebook link**
