### ISSUE TITLE
Chinafy - Missing Chinafy link

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People#209]
(reported by @adamcogan)

The SSW People mini site has been Chinafied, there should be a link in the footer to the rules

- [ ] add a link to https://rules.ssw.com.au/rules-to-better-internationalization (similar to SugarLearning)

![image](https://user-images.githubusercontent.com/600044/86547451-65068f00-bf7c-11ea-9f61-75fc664c99bc.png)
**Figure: SugarLearning has a Chinafied link in the footer with a link to the rules**

**Comment by SebastienBoissiere** [comment]
Added to [PBI 54471](https://dev.azure.com/ssw/SSW.People/_workitems/edit/54471/)

**Comment by SebastienBoissiere** [comment]
Hi @wicksipedia 
CC @adamcogan 

This closes #209.

The link to the rule has been added to the footer.

![image](https://user-images.githubusercontent.com/28290353/87626200-238d9500-c76f-11ea-9cbf-d85fef208b80.png)
**Figure: Chinafied link in the footer**
