### ISSUE TITLE
Footer - Promote other people to use the project

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People#210]
(reported by @adamcogan)

In the footer, change from:
   We ❤ open source. This page is on GitHub 

To:
  We ❤ open source. Fork this on GitHub and start using it for yourself.

**Comment by SebastienBoissiere** [comment]
Added to [PBI 54467](https://dev.azure.com/ssw/SSW.People/_workitems/edit/54467/)

**Comment by SebastienBoissiere** [comment]
Hi @wicksipedia 
CC @adamcogan 

**Done**, this closes #210

The message has been changed from:
We ❤ open source. This page is on GitHub

To:
We ❤ open source. Fork this on GitHub and start using it for yourself.

![image](https://user-images.githubusercontent.com/28290353/87625721-32277c80-c76e-11ea-9976-3c62c765299c.png)
**Figure: Now we promote the use of SSW.People**
