### ISSUE TITLE
Skills Sorting - Sort Advanced and Intermediate Skills

### ISSUE THREAD

**Issue by ozdemir-mehmet** [SSWConsulting/SSW.People#218]
The skills in their relevant sections don't seem to sorted in any particular order (are these maybe in creation order). In the absence of a sort order within Advanced and Intermediate sections, sort these alpha order within each section.

![image](https://user-images.githubusercontent.com/37358029/87118673-53482300-c2bf-11ea-9411-f17a2bf67ff3.png)

**Comment by SebastienBoissiere** [comment]
Hi @ozdemir-mehmet 
CC @adamcogan 

**Done**, this closes #218

The skills within Advanced and Intermediate sections are now ordered using the field 'Sort Order' if it exists.
![image](https://user-images.githubusercontent.com/28290353/88002340-a6369b80-cb45-11ea-9b53-dfacc09a522f.png)
**Figure: Mehmet skills are sorted using 'Sort Order'**

If 'Sort Order' is empty, the alpha order is used
![image](https://user-images.githubusercontent.com/28290353/88002467-f281db80-cb45-11ea-88a8-8b19d663b46a.png)
**Figure: Brendan's skills doesn't have the 'Sort Order' field filled so the alpha order is used**
