### ISSUE TITLE
People-cn indexed instead of people

### ISSUE THREAD

**Issue by kikibianc** [SSWConsulting/SSW.People#220]
Hey @SebastienBoissiere,
cc: @adamcogan @calumjs @christianmorfordwaitessw 

I looked for “kiki ssw” in Google today and found that the result showed people-cn link instead of people, take a look at this quick gif for what I see:

![PeopleCNIndex4](https://user-images.githubusercontent.com/5884297/87216618-be0f6200-c384-11ea-8fa9-bbf19a0ab1b0.gif)

Result example:

    ssw.com.au › people-cn › kaique-biancatti
    Kiki is one of those rare Sys Admins who is a Powershell Guru. He has been an Infrastructure Analyst at SSW for many years, and he has taken some of our ...

Expected:

    ssw.com.au › people › kaique-biancatti
    Kiki is one of those rare Sys Admins who is a Powershell Guru. He has been an Infrastructure Analyst at SSW for many years, and he has taken some of our ...

1. Can you check why people-cn is being indexed?
2. Is this happening to everyone?
3. The gif took a little trouble, did it help at all?

**Comment by SebastienBoissiere** [comment]
Created [PBI 54736](https://dev.azure.com/ssw/SSW.People/_workitems/edit/54736/)

**Comment by SebastienBoissiere** [comment]
Hi @kikibianc 
CC @adamcogan 

**Done**, this closes #220.

The following code was added to all the pages of people-cn to prevent indexing from search engines:
```html
<meta name="robots" content="noindex">
```
![image](https://user-images.githubusercontent.com/28290353/87636200-b9331f80-c783-11ea-85be-0a9953619d03.png)
**Figure: Searching Kiki on Google doesn't return people-cn anymore**
