### ISSUE TITLE
Can we get all badge clickable and jump to a specific website?

### ISSUE THREAD

**Issue by VictorYMH** [SSWConsulting/SSW.People#232]
Currently when I click a badge like "AngularHackday", Website will lead me to https://angularhackday.com
but if I click DevOps badge or Anglar badge. it will just open the image in a new window

**Comment by christianmorfordwaitessw** [comment]
Hi @VictorYMH,

Anyone can make the badges on their profile hyperlink to a website.  
For example to create the Angular clickable badge you can use the following markdown:
```
[[imgBadge]] | [![angular-logo.png](../badges/Developer-angular.png)](https://angular.io)
```
 I have added the instructions to the Wiki for creating clickable badges.
See - https://github.com/SSWConsulting/SSW.People.Profiles/wiki/6.-Extras-%E2%80%90-Editing-profiles#extra---badges
![image](https://user-images.githubusercontent.com/56522256/88499113-4ee27080-d008-11ea-8920-0ae07a023e18.png)
**Figure: Added instructions for hyperlinked badges**
