### ISSUE TITLE
Profile - print css formatting

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People#259]
Cc: @adamcogan 

When I print a profile:
1. The horizontal divider under the quote doesn't span the entire width
  Delete it
2. It isn't clear that the quote is a quote
  Add quote markers
3. Hide YouTube videos or replace with cover art

Recommendation:

![image](https://user-images.githubusercontent.com/600044/89843287-854ced80-dbbb-11ea-95a7-66b34d9f5764.jpeg)

[AB#56166](https://ssw.visualstudio.com/00f23d37-efb4-45db-8a76-56aba33a8301/_workitems/edit/56166)

**Comment by SebastienBoissiere** [comment]
Hi @wicksipedia 
CC @adamcogan 

> 1.The horizontal divider under the quote doesn't span the entire width
    Delete it

**Done**, I aslo moved the quote under the photo and it takes all the width

> 2.It isn't clear that the quote is a quote
    Add quote markers

**Done**
> 3.Hide YouTube videos or replace with cover art

**Done**, the Youtube videos have been removed

This closes #259.

![image](https://user-images.githubusercontent.com/28290353/91684928-2e27b080-eb9c-11ea-8de0-b42a8eb69ff7.png)
**Figure: The divider was removed, the quote moved under the photo and quotes added**
