### ISSUE TITLE
Profile - print css - events

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People#260]
Cc @adamcogan 

When I print a profile and look at events:

1. Events are not aligned
2. Event headings look too big

![image](https://user-images.githubusercontent.com/600044/89843521-4d927580-dbbc-11ea-8bc7-d94b8b836747.jpeg)

[AB#56164](https://ssw.visualstudio.com/00f23d37-efb4-45db-8a76-56aba33a8301/_workitems/edit/56164)

**Comment by SebastienBoissiere** [comment]
Hi @wicksipedia 
CC @adamcogan 

> 1. Events are not aligned

I couldn't reproduce it on Edge, Chrome, Firefox. After talking with Nick, he couldn't reproduce it too.

> 2. Event headings look too big
**Done**, I reduced the font size from 1.5rem to 1.25 rem

![image](https://user-images.githubusercontent.com/28290353/91688549-9333d400-eba5-11ea-8fa8-4c86c107d621.png)
**Figure: Font has been reduced, no alignment issue on the events**

This closes #260
