### ISSUE TITLE
Profile - responsive css - layout

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People#261]
cc @adamcogan @sswrebeccaliu @tiagov8 

As per our conversation on email - we'd like:
1. when viewing the profile on a phone - swap the quote/social links sections

![image](https://user-images.githubusercontent.com/600044/89961557-631fa200-dc85-11ea-937b-d6d86338608e.png)

[AB#56165](https://ssw.visualstudio.com/00f23d37-efb4-45db-8a76-56aba33a8301/_workitems/edit/56165)

**Comment by SebastienBoissiere** [comment]
Hi @wicksipedia 
CC @adamcogan 

**Done**, this closes #261

The quote and the social links are swapped on mobile.

![image](https://user-images.githubusercontent.com/28290353/91682313-7511a800-eb94-11ea-97d7-ea761dde611c.png)
Figure: Social links and quote have been swapped

**Comment by SebastienBoissiere** [comment]
Reopen as Devops doesn't like the closed issues on GitHub
![image](https://user-images.githubusercontent.com/28290353/91683625-7644d400-eb98-11ea-8631-7efcfdf5a94f.png)
Figure: PBI is replaced by 'unparented'
