### ISSUE TITLE
Data - sample profile not displaying correctly

### ISSUE THREAD

**Issue by christianmorfordwaitessw** [SSWConsulting/SSW.People#265]
The sample profile is not rendering all the data
https://ssw.com.au/people/sample

It is missing:
- Name
- Social links
- Edit button

![image](https://user-images.githubusercontent.com/56522256/91125715-b95cfe00-e6e5-11ea-87e3-0375f6eaa14e.png)
**Figure: Sample profile missing data**

[AB#56158](https://ssw.visualstudio.com/00f23d37-efb4-45db-8a76-56aba33a8301/_workitems/edit/56158)

**Comment by SebastienBoissiere** [comment]
Hi @christianmorfordwaitessw 
CC @adamcogan 

**Done**, this closes #265

Data for the sample profile data are now mocked in a Json file.

![image](https://user-images.githubusercontent.com/28290353/91916932-d3a86480-ed01-11ea-97fd-fbdfc3ceb479.png)
**Figure: Sample profile has been fixed**
