### ISSUE TITLE
Couldn't download Nick's image

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#279]
Today I tried to download Nick's photo from https://www.ssw.com.au/people/nicholas-viet and got a 404:
<img width="929" alt="Screen Shot 2020-09-02 at 1 07 56 PM" src="https://user-images.githubusercontent.com/12601228/92031438-77ebd480-ed1d-11ea-9269-22bfb6ae2f27.png">

https://www.ssw.com.au/people/static/Nicholas-Viet-Sketch-269f991294fa9cd6cfb2cc146169f4d6.jpg 

[AB#56449](https://ssw.visualstudio.com/00f23d37-efb4-45db-8a76-56aba33a8301/_workitems/edit/56449)

**Comment by SebastienBoissiere** [comment]
Hi @tiagov8 
CC @adamcogan 

**Done**, thi closes #279.

I changed the name of the containing his profile. His display name and his folder didn't match. As we build the URL for the image from the display name, the URL was incorrect.
