### ISSUE TITLE
UI - Make alumni status more obvious

### ISSUE THREAD

**Issue by SebastienBoissiere** [SSWConsulting/SSW.People#309]
To: @BrandlD , @tiagov8 
CC: @adamcogan , @christianmorfordwaitessw 

As per our conversation, we need something on a past employee profile to make it obvious they are past employees.

1. Add an emoji or a label to past employee's profiles

![image](https://user-images.githubusercontent.com/28290353/94530791-eec5b000-027e-11eb-8977-137d978e5d3a.png)
**Figure: Past employee's profile**

[AB#57225](https://ssw.visualstudio.com/00f23d37-efb4-45db-8a76-56aba33a8301/_workitems/edit/57225)

**Comment by tiagov8** [comment]
Hi team, 

I am personally not a big fan of the icon/emoji approach.

I suggest making alumni profiles all in B&W by using CSS grayscale. E.g:

<img width="1635" alt="Screenshot 2024-02-21 at 10 23 06 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/d68ae3c7-55a2-4a34-af65-1f10881eeaaa">

**Comment by Aibono1225** [comment]
Cc: @JackDevAU 

As per my conversation with @tiagov8 , we are going to use a tag and icon next to the title to indicate alumni status

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/7269d7ee-7b31-42dd-9795-e57240a4fcf5)

**Comment by JackDevAU** [comment]
Not a huge fan of the current tag. But do like the concept! 

New Tag + greyscale = maybe perfect? 😂

**Comment by tiagov8** [comment]
> Not a huge fan of the current tag. But do like the concept!
> 
> New Tag + greyscale = maybe perfect? 😂

greyscale was not very well accepted between other designers. Maybe we can revisit if we need to make it even more obvious

**Comment by Aibono1225** [comment]
Done - 

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/7cf15be1-6150-48f8-8127-1231352ba14c)
