### ISSUE TITLE
Patrick Zhao's profile

### ISSUE THREAD

**Issue by PatrickZhao1989** [SSWConsulting/SSW.People#316]
Hello team,

My CRM profile and SSW People site content does not match.

![image](https://user-images.githubusercontent.com/46980570/101463328-60159380-3991-11eb-9bb9-0c3c9afeb9a3.png)
Figure: CRM page
![image](https://user-images.githubusercontent.com/46980570/101463419-7f142580-3991-11eb-94ca-520325ddef88.png)
Figure: SSW People site

I tried to add a new skill and I've received an email notification saying change will come through soon. But I have not seen any update in 10 minutes.

[AB#58894](https://ssw.visualstudio.com/00f23d37-efb4-45db-8a76-56aba33a8301/_workitems/edit/58894)

**Comment by SebastienBoissiere** [comment]
To:@PatrickZhao1989 
CC: @christianmorfordwaitessw 

**Fixed**
We noticed 2 issues on your profile, after fixing them, your skills list is correct: 
1. Some of your skills were inactive but still displayed on your profile. These skills have been deleted. I created an issue to add to wiki that skills should be deleted: https://github.com/SSWConsulting/SSW.People.Profiles/issues/417
![image](https://user-images.githubusercontent.com/28290353/101556886-ec669b80-3a0f-11eb-943a-e0b81308273a.png)
**Figure: Inactive skills**
2. HTML5 was appearing twice, one had the name 'CSS - Advanced'
![image](https://user-images.githubusercontent.com/28290353/101556929-06a07980-3a10-11eb-8770-faeac53282ee.png)
**Figure: The second HTML5 was for CSS-Advanced**
