### ISSUE TITLE
UI - Add Newcastle office filter

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People#318]
CC @adamcogan 

Since we have an office in Newcastle, we should advertise it on SSW.People

![image](https://user-images.githubusercontent.com/600044/105457353-cbfe5200-5cda-11eb-8438-62bf52949001.jpeg)
**Figure: I work in the Newcastle office but you wouldn't know that from the filters**

[AB#59373](https://ssw.visualstudio.com/00f23d37-efb4-45db-8a76-56aba33a8301/_workitems/edit/59373)

**Comment by christianmorfordwaitessw** [comment]
To: @wicksipedia 
Cc: @adamcogan 

Hi @wicksipedia,

> Since we have an office in Newcastle, we should advertise it on SSW.People

**Done** - See https://www.ssw.com.au/people/?location=Newcastle
![image](https://user-images.githubusercontent.com/56522256/107460517-5df7cd00-6bac-11eb-8dba-be54fd31e4f0.png)
**Figure: Newcastle office filter on SSW People**
