### ISSUE TITLE
UI - Add Favicon to SSW.People

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#321]
Noticed SSW.People site doesn't have a favicon:

<img width="536" alt="Screen Shot 2021-03-22 at 3 48 24 PM" src="https://user-images.githubusercontent.com/12601228/112068020-49e9a880-8b26-11eb-9218-176830f3fff6.png">

1. Please add the SSW squares ([SSW.Rules](https://www.ssw.com.au/rules) is a good example)

[AB#60584](https://ssw.visualstudio.com/00f23d37-efb4-45db-8a76-56aba33a8301/_workitems/edit/60584)

**Comment by christianmorfordwaitessw** [comment]
Hi @tiagov8,

> 1. Please add the SSW squares (SSW.Rules is a good example)

**Done** - favicon is appearing in the browser tab
![image](https://user-images.githubusercontent.com/56522256/120271536-db2b8700-c2ee-11eb-849e-4623e572888b.png)
**Figure: favicon showing in Chrome**

![image](https://user-images.githubusercontent.com/56522256/120271591-f39ba180-c2ee-11eb-911e-a13537b681d1.png)
**Figure: favicon showing in Edge**

-Christian
