### ISSUE TITLE
The GitHub action for creating employee profiles is not working

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#324]
@christianmorfordwaitessw @bradystroud 

The GitHub action for creating employee profiles is not working. It has not run in 11 months, this needs to be investigated.

![image](https://user-images.githubusercontent.com/79821522/117614875-4977a080-b1ac-11eb-8127-f6f9b16b0a1b.png)
**Figure: the create employee profile action which is not working**

**Comment by JackDevAU** [comment]
Closing stale issue. 

Hey @pierssinclairssw 

I had a quick look and it seems this action is not being used https://github.com/SSWConsulting/SSW.People.Profiles/actions/workflows/create_profile.yml

1. Please reopen if this is still an issue
