### ISSUE TITLE
SSW.People build is throwing a fatal error because it is running out of memory

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#325]
SSW.People is building successfully but throwing a fatal out of memory error during the build process. This problem needs to be investigated.

![image](https://user-images.githubusercontent.com/79821522/117617974-a7a68280-b1b0-11eb-94d5-ef5e9692d808.png)
**Figure: The fatal error in the build**

**Comment by christianmorfordwaitessw** [comment]
Hi @pierssinclairssw,

This is no longer occurring in the builds so I'll close this issue.

-Christian
