### ISSUE TITLE
SSW.People profile email updates

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#330]
Hi Seb,

Can you please make the following changes to the rules email? (note I’ve also incorporated Adam’s change too)

1.	Change from
Hi Tiago,

You have made a change to CRM | User | Adam
These changes will appear in SSW People after 30 mins.
Thanks for updating, it will be live soon

More information about this rolling build can be found here
https://raw.githubusercontent.com/SSWConsulting/SSW.People.Profiles/main/.github/instructions/images/rolling_build.png

-- Powered By CRM.SSWPeople
To
Hi Tiago,

Thanks for your updates to SSW People | Adam. These changes will be live after about 30 mins.

This happened because you made a change to CRM | User | Adam. More information about this rolling build can be found here
https://raw.githubusercontent.com/SSWConsulting/SSW.People.Profiles/main/.github/instructions/images/rolling_build.png

-- Powered By CRM.SSWPeople
           https://github.com/SSWConsulting/SSW.People  (an open source project by www.ssw.com.au )

![image](https://user-images.githubusercontent.com/79821522/118416215-e200aa00-b6f1-11eb-8332-d3393bd2cb2e.png)
**Figure: the change with highlighting because GitHub doesn't support highlighting text aside from code blocks**

**Comment by christianmorfordwaitessw** [comment]
Cc: @adamcogan @UlyssesMaclaren 
Hi @pierssinclairssw,

> 1. Can you please make the following changes to the email template

**Done** - See image below
![image](https://user-images.githubusercontent.com/56522256/121126297-4c2cea80-c86b-11eb-812b-0198fa8589d6.png)
**Figure: SSW.People email notification**

-Christian
