### ISSUE TITLE
CRM Skill Changes cause duplicate deployment email

### ISSUE THREAD

**Issue by Hona** [SSWConsulting/SSW.People#336]
CC: @bradystroud 

Hi,

When adding skills in the CRM, a duplicate email is triggered.

1. Only send one email on skill change

![image](https://user-images.githubusercontent.com/10430890/128815032-175918ad-a055-4660-bdcb-597f9d160316.png)
**Figure: Email showing duplicate emails (see timestamps)**

-Luke

**Comment by JackDevAU** [comment]
Closing stale issue

Hi @Hona 

1. Please reopen if this is still an issue
