### ISSUE TITLE
Profile Automation - Profile creation flow is not working

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#337]
CC @leahy268 @christianmorfordwaitessw @adamcogan @bradystroud 
As per my conversation with Warwick, Christian and Brady on August 19th, when users try to run the Automated profile creation flow, they run into an issue with the Azure KeyVault connection

- [ ] Investigate and fix the Azure KeyVault connection

![image](https://user-images.githubusercontent.com/79821522/131272440-aec36733-32ba-4cb3-81a1-34768f53882d.png)
**Figure: Users click on Flow | Create SSW.People profile but are unable to proceed further due to an invalid Azure KeyVault connection**

**Comment by tkapa** [comment]
CC: @JackDevAU @tkapa 

Adding myself and Jack as we encountered the same issue.

**Comment by JackDevAU** [comment]
Closing stale issue. 

Hey @pierssinclairssw 

1. Please reopen if this is still an issue
