### ISSUE TITLE
Profile Automation - Creating Profile Wiki is unclear

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#338]
CC @leahy268 @christianmorfordwaitessw @adamcogan @bradystroud
As per my conversation with Warwick, Christian and Brady on August 19th, when users go through SugarLearning and navigate to the Wiki it is unclear how to reach the profile creation section or when they have finished.

- [ ] Add a part at the end of the profile creation Wiki to contact someone to review your Pull Request.
- [ ] Review the Wiki to make sure the end-to-end process for creating profiles is Crystal clear from the home page.
- [ ] On [SugarLearning](https://my.sugarlearning.com/SSW/items/9363/github-create-your-employee-profile-not-for-work-experience), change the navigation to more clearly point to instructions on profile creation.
e.g. it should directly link to a wiki page that explains it.
- [ ] Get the Wiki and SugarLearning changes checked by someone unfamiliar with the process and non-technical
- [ ] Investigate if we can add Automated Reviewers to our Pull Requests and if this is a good idea.
- [ ] If the above was a good idea then implement it.
- [ ] Get this all checked by @adamcogan 

![image](https://user-images.githubusercontent.com/79821522/131273697-5c388ec6-579c-48c9-b4c2-456d6368240e.png)
**Figure: It is not clear what else I need to do before my profile is done e.g. create a Pull Request and have it reviewed**

![image](https://user-images.githubusercontent.com/79821522/131273740-cd018e61-362b-4692-9574-c15eef6658c2.png)
**Figure: SugarLearning doesn't clearly communicate the process which makes it hard for users to follow.**

**Comment by JackDevAU** [comment]
Closing stale issue. 

Hi @pierssinclairssw 

The SL item seems to have been updated and the wiki seems pretty through.

1. Please reopen if this is still a requested feature
