### ISSUE TITLE
Profile Automation - Automatic notification when profile changes should be live

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#339]
CC @leahy268 @christianmorfordwaitessw @adamcogan @bradystroud @wicksipedia 
As per my conversation with Warwick, Christian and Brady on August 19th, when users make a change to their profile it is very unclear whether or not their changes should be live. From their perspective they get an email saying changes were made but it doesn't give them any indication on if the changes should already be live or not. To address this problem we should implement some kind of automated email notification to indicate that changes are deployed.

- [ ] When a flow is triggered from people add the user who triggered it to a subscription list
- [ ] When the next rolling build is triggered we send out an email to those on the subscription list to say the build has been triggered and should go live in 20 minutes and then clear the subscription list.
- [ ] Investigate if we should extend this further by sending a notification when the deployment itself is complete and implement it if it makes sense.

See the below diagram for details of the process:
![](https://raw.githubusercontent.com/SSWConsulting/SSW.People/main/_docs/images/SSW.People-CICD-Diagram.png)
**Figure: The process for triggered people profile changes**

**Comment by JackDevAU** [comment]
Closing stale issue. 

Hi @pierssinclairssw 

We currently have an email that is sent out and another PBI to improve it: https://github.com/SSWConsulting/SSW.People/issues/542

1. Please reopen if this is still requested.
