### ISSUE TITLE
🐛 Profiles | Ordering is wrong

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#340]
@UlyssesMaclaren @bradystroud @christianmorfordwaitessw 

1.	On https://www.ssw.com.au/people/, the devs should show in order of job title:
•	Solution Architects
•	Senior Software Architects
•	Software Architects
•	Senior Software Developers
•	Software Developers

Note: this is already partially done but some of the people are jumbled

**Comment by JackDevAU** [comment]
Closing as this seems to be fixed
