### ISSUE TITLE
📃Roles | SSW People should link off to our Roles repo

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#341]
@UlyssesMaclaren @christianmorfordwaitessw @bradystroud 

On SSW People it should link off to our [SSW Roles Repo](https://github.com/SSWConsulting/SSW.Roles) which explains what all our roles mean.

1. 2.	Add a link to https://github.com/SSWConsulting/SSW.Roles next to "Developers" as “About our Roles”:

![image](https://user-images.githubusercontent.com/79821522/133008057-2de19aef-1aaa-4cb2-9d7e-02ae65df28ea.png)
**Figure: Add link to what the roles mean**

**Comment by JackDevAU** [comment]
Closing stale issue. 

Hey @pierssinclairssw 

I had a quick look over at https://github.com/SSWConsulting/SSW.Roles and not every role is mentioned there. 

1. Please reopen if this is still requested
