### ISSUE TITLE
UI - Make "Edit/Info" links/buttons consistent with SSW.Rules

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#343]
Hi team,

1. Please update the "Edit" and "Info" links on a SSW.People profile ([example](https://www.ssw.com.au/people/jayden-alchin)) to be consistent with SSW.Rules ([example](https://www.ssw.com.au/rules/dynamics-crm-install-the-dynamics-365-app-for-outlook))
2. The URL for the info, should also change to point to [SSW.People wiki](https://github.com/SSWConsulting/SSW.People.Profiles/wiki) Please action

from
<img width="1424" alt="Screen Shot 2021-09-20 at 2 31 30 PM" src="https://user-images.githubusercontent.com/12601228/134078842-6b658722-58de-42d5-8da8-cb5e40e3439a.png">

to
<img width="1201" alt="Screen Shot 2021-09-20 at 2 35 02 PM" src="https://user-images.githubusercontent.com/12601228/134079042-95a963d9-bb76-4ee3-93d9-eeeac8f083ce.png">

**Comment by Aibono1225** [comment]
Done - please see below:

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/b32d8b1f-8593-488f-9e71-d0d80cfda600)


Please let me know if more changes are needed 🙂
