### ISSUE TITLE
BUG - empty skill

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#344]
Hi team,

There is an empty skill on the list... which although have "(0)" shows Tim under it...

1. Please fix https://www.ssw.com.au/people/?skill=&skill= 

<img width="765" alt="Screen Shot 2021-09-20 at 2 40 52 PM" src="https://user-images.githubusercontent.com/12601228/134079747-df55d6f2-1393-4e30-a67c-a6cd9bca8086.png">

**Comment by christianmorfordwaitessw** [comment]
Hi @tiagov8,

> 1. Please fix https://www.ssw.com.au/people/?skill=&skill=

**Done** - The empty skill is no longer showing
See https://www.ssw.com.au/people/?skill=&skill=

![image](https://user-images.githubusercontent.com/56522256/148137194-0ecae417-2486-4a61-9e20-60d96148e739.png)
**Figure: Empty skill no longer showing**
