### ISSUE TITLE
🔨 Fix empty Upcoming Speakers list

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#346]
Hi team,

I don't think we should have that empty "Upcoming Speakers" heading on the sidebar...

Not sure if it is a bug (not showing stuff) OR if we really don't have any upcoming events added to the calendar.

Either way, the user shouldn't see this empty
1. Please action
   a) Add the upcoming Speakers
   OR
   b) Hide that section for the time being
   
<img width="601" alt="Screen Shot 2021-09-20 at 3 03 04 PM" src="https://user-images.githubusercontent.com/12601228/134081964-9f7a0f77-ebdb-4dab-9ec9-aa8a7e73f6e9.png">

**Comment by JackDevAU** [comment]
Hey @Aibono1225 

Tested this in staging and it looks great! 

Awesome stuff!

1. Please deploy to production

**Comment by Aibono1225** [comment]
> 1. Please deploy to production

Done ⭐ - We can now find our upcoming speakers on the page:

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/de6bf26f-1d0a-48d0-adfe-9cb7d810e35f)
