### ISSUE TITLE
Can we improve the skills list?

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#347]
cc @adamcogan @camillars @UlyssesMaclaren @jaydenalchin @2fernandez 

Hi team,

I think we are giving user way too many options under "Skills""

https://zoovu.com/blog/psychology-choice-customers-need-assistance/

IMO we should aim to:
- Merge some related items
   - E.g. "After Effects", "Premiere", "Cinematography" into "Video Recording and Production"
   - E.g. We have 7 items with ".NET" and 15 with "Azure"
    
- Not show items that are not very relevant to our major prospect/existing clients 
   - E.g. [Tax and Accounting](https://www.ssw.com.au/people/?skill=Tax-and-Accounting) 
   - E.g. [Canva](https://www.ssw.com.au/people/?skill=Canva)
   
- Not show items that are too subjective:
   - E.g. [Support](https://www.ssw.com.au/people/?location=All&skill=Support) 

**Note:** I understand that internally the specific skills are important to have, so we would probably need to change the way these are included into the page in the back-end. Might be a big one, but I think it definitely is worth it!

--

<img width="710" alt="Screen Shot 2021-09-20 at 3 27 21 PM" src="https://user-images.githubusercontent.com/12601228/134084174-497f8d29-d064-4978-9473-a12369c3ebb0.png">

<img width="731" alt="Screen Shot 2021-09-20 at 3 27 11 PM" src="https://user-images.githubusercontent.com/12601228/134084170-f0a979a6-9988-44f4-8764-e1a586322963.png">

**Comment by JackDevAU** [comment]
Closing as this is a duplicate and has been superseded by https://github.com/SSWConsulting/SSW.People/issues/496

**Comment by tiagov8** [comment]
Hi @JackDevAU 

Looking at the other Issue, it talks about merging source of skills, but not about reducing the number of displayed skills, which is my goal here.

- [ ] 1. Please reopen if you agree (I might have missed something in the other Issue)

**Comment by camillars** [comment]
@tiagov8 

+1 to this - maybe we need to talk to @zl24622 to understand how we can limit the skills (and not allow anyone to add new ones without a request to the CRM team)

**Comment by JackDevAU** [comment]
CC @Aibono1225 @bradystroud @zl24622 @piers-sinclair 

Hey Team, 

As per my conversation with @bradystroud we are going to implement this as the following, 

**Add a Highlight skill field to CRM (then order by # of people)**
- [ ] Add a new field to the skills table in CRM called "Highlight skill" 
- [ ] Filter by this new "Highlight skill" then by the # of people associated with that skill


Hey @zl24622, 

1. Please add a new field to the Skills table in CRM called `Highlight skill`

**Comment by Aibono1225** [comment]
As per my conversation with @zl24622 via Teams chat, the new field `Highlight skill` will be added to the next week's backlog

**Comment by zl24622** [comment]
> As per my conversation with [@zl24622](https://github.com/zl24622) via Teams chat, the new field `Highlight skill` will be added to the next week's backlog

Added a PBI in the CRM team backlog. Working on it this sprint.

**Comment by Aibono1225** [comment]
Update:

The "Highlight skill" has been added to CRM, see screenshot below:
![Image](https://github.com/SSWConsulting/SSW.People/assets/127192800/6f489712-f200-4878-828e-48328d932224)


I've created a pull request to make the list sorted by this new field and then by the number of people. 
PR link: https://github.com/SSWConsulting/SSW.People/pull/641

**Comment by JackDevAU** [comment]
✅ Done!

@Aibono1225 has done an awesome job and we now have "Highlighted Skills" that affect the order of technologies. 

- Technologies are now sorted via - "Highlight skill"
- Then by the # of people associated with that skill


See below:

![Image](https://github.com/SSWConsulting/SSW.People/assets/57518417/d8153ed8-8c86-48cc-9d10-a9e9832145d5)
**Figure: 🦙 TinaCMS skill shown at the top as its the only "highlighted skill"**
