### ISSUE TITLE
BUG - Kiki's image have different sizes

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#349]
Hi team,

https://www.ssw.com.au/people/kiki 

Kiki's coloured image has a non-standard size (aspect ratio)

1. Please fix

![kiki-image-sswpeople-issue](https://user-images.githubusercontent.com/12601228/134432460-7d2cc438-ddcd-48a8-9d57-c594ef5dc5c3.gif)

**Comment by tiagov8** [comment]
Hey @kikibianc Has your photo been updated?

**Comment by christianmorfordwaitessw** [comment]
> 1. Please fix

**Done** - I have resized the image
See https://www.ssw.com.au/people/kiki
![2022-01-12_16-08-36](https://user-images.githubusercontent.com/56522256/149067493-2d98c805-2b4e-437a-bd13-75bb039a2849.gif)
**Figure: Image now has the same size**
