### ISSUE TITLE
GitHub Widget - Investigate cause of errors and when it fails display nothing instead of an error

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#352]
@calumjs @Berber-Mama @adamcogan @christianmorfordwaitessw @bradystroud 

Yang just spotted this weird issue on Calum's SSW people page – the GitHub contributions says “Error :(“

When Calum went to check it for himself, it worked fine. Apparently Yang has the same issue on everyone’s page, so it’s not just Calum's.

Adam also experienced the same issue as Yang in the past but hasn't been able to reproduce the issue recently.

- [ ] Please investigate…maybe something to do with a VPN connection, etc.
- [ ] See if we can make it so if widget's fail, they are just hidden instead of displaying an error. 

![image](https://user-images.githubusercontent.com/79821522/138970100-21e978a4-f976-4a80-82a8-53572f3e2381.png)
**Figure: Yang’s view has an error**

![image](https://user-images.githubusercontent.com/79821522/138970107-679f2923-f0ca-4ac9-9b84-030a1b918d03.png)
**Figure: My view works fine**

**Comment by JackDevAU** [comment]
Closing as this has been fixed
