### ISSUE TITLE
💄UI - Improve "Latest Rules" section on sidebar

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#369]
cc: @Geordie88 

---

Hi team,

The Latest Rules section on the sidebar of a profile in SSW.People (e.g.: https://www.ssw.com.au/people/bryden-oliver) looks heavy and cluttered...

<img width="283" alt="Screen Shot 2022-01-27 at 5 53 13 PM" src="https://user-images.githubusercontent.com/12601228/151442106-a5bb3276-19e0-4d74-a09b-5d178fe59d84.png">

... the same "widget" on [Rules homepage](https://www.ssw.com.au/rules/) looks way cleaner:

<img width="582" alt="Screen Shot 2022-01-27 at 5 53 08 PM" src="https://user-images.githubusercontent.com/12601228/151442234-713c6cbc-5fe5-4137-898e-d98d4e47fddd.png">

1. Please apply the design from SSW.Rules on SSW.People

**Comment by tiagov8** [comment]
cc @Geordie88 

Hey @bradystroud  

Looks like this was actioned... but still Issue is still Open here... was it you?

<img width="637" alt="Screenshot 2023-03-06 at 12 30 26 PM" src="https://user-images.githubusercontent.com/12601228/223223700-91ea453a-1aab-4fa6-9a5c-b96c5e64de36.png">

**Comment by tiagov8** [comment]
Hey @bradystroud 

Based on a feedback from @amankumarrr 

I think the term "Latest Rules" may not be accurate since the list shown here is for rules edited/created by the person profile. This is not clear.

1. Can we change from

**LATEST RULES** 

to

**MY RULES** 
or
**ASSOCIATED RULES** 

?

2. I would also have only 6 instead of 10 to avoid scrolling with no content. Example:

  <img width="1450" alt="Screenshot 2023-03-06 at 12 38 38 PM" src="https://user-images.githubusercontent.com/12601228/223225357-5f0d936a-3b4e-4dd3-9f75-d01eec5c7755.png">

**Comment by bradystroud** [comment]
cc @BrookJeynes @amankumarrr 
Hey @tiagov8 

Thanks for the feedback 🙂
I created issues to cover all these tasks

- [ ] https://github.com/SSWConsulting/SSW.Rules.Widget/issues/28
- [ ] https://github.com/SSWConsulting/SSW.People/issues/474
- [ ] https://github.com/SSWConsulting/SSW.People/issues/475
- [ ] https://github.com/SSWConsulting/SSW.Rules.Widget/issues/29

Closing this one as the original issue is fixed
