### ISSUE TITLE
📄Report - Schedule an Email that shows people all the skills they have selected and the ones they haven’t

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#372]
(Updated to reflect email from @adamcogan )
cc @ozdemir-mehmet, @leahy268 

Hi @drwharris ,

As per our conversation with @adamcogan @christianmorfordwaitessw @UlyssesMaclaren @calumjs @brydeno @JeanThirion SSW people skills has a lot of poor quality data. The problems include:

- Data Quality Control - The skills are not quality controlled meaning there is a lot of junk for example:
  - Duplication - There are skills that should be consolidated into one so the page is easier to navigate and people always add the same skill 
e.g. (Blazor, BlazorServer, Blazers) or (SQL Server, Microsoft SQL Server)
  - Relevancy - There are a lot of skills that aren’t particularly relevant to our clients 
e.g. C++, Copywriting, Skype for Business, Unity Engine etc
  - Scope - There are very vague skills which don’t give much information to a client
e.g. Support, Employee relations, Networking
  - Incorrect data - There are improperly named skills because anyone can add them 
e.g. .NET EF Core exists but this is not a real skill, it should be just EF Core

This poor data affects the UX of SSW People because there are too many things to look through and the searching/filtering capability is compromised. For example, skill duplication means that when clients filter, they will miss people who haven’t added the alternative skills or the employees will need to add all alternatives polluting their profile with data.

![image](https://user-images.githubusercontent.com/79821522/151735489-12f19c74-b85d-4f9c-b54a-cc86ede1fcb0.png)
**Figure: Luke has been forced to add 3 different types of Blazor here, so clients filtering to Blazor can find him**

- [ ] Send a report, via email to all active employees on a monthly basis to remind them to keep their list of skills in CRM current. Include in the email:
  - [ ] The current list of the users skills
  - [ ] The list of skills they haven't selected
  - [ ] Whether each skill is associated with a consulting page (pulled from the json file @christianmorfordwaitessw made

The following is an example template for the email

> Hello {{user}},
> 
> Its really important to keep your listed CRM skills current and relevant. Remember to add to your list any new skills you may have acquired and remove any skills you think are no longer considered current or relevant.
> 
> Please review the following lists. Note that skills highlighted are in demand.
> 
> Your Skills
> Skill 1
> Skill 2
> Skill 3
> ...
> Skill 9
> Available Skills
> Skill A
> Skill B
> Skill C
> ...
> Skill Z
> To update your skills, click here.

ZZ

- [ ] ~~Add a view or report to show a comparison of the skills a person has selected vs the ones they haven't. Make sure it provides:~~
  - [ ] ~~A list of all skills available~~
  - [ ] ~~Whether each skill is associated with a consulting page (pulled from the json file @christianmorfordwaitessw made~~
  - [ ] ~~Whether the skill has been selected~~

**Comment by drwharris** [comment]
CC @christianmorfordwaitessw @UlyssesMaclaren @calumjs @brydeno @ozdemir-mehmet @leahy268 @pierssinclairssw 

Hi @adamcogan 

As per discussion with @JeanThirion, I am confused about what is being asked for here and the benefit it would bring. The current request is to build a PowerBI report that I am guessing would sit in the SSW Reports folder. 

![image](https://user-images.githubusercontent.com/19632724/152099857-91413d9b-23f1-48c3-8ed4-27b90e6ebcbd.png)
**Figure:** Where the report might go

I question what benefit this would bring. Who is going to run the report? And for the effort, are we getting any value and solving an actual issue?

I feel we would better achieve the intention of this issue by creating scheduled email (once a month?) along the lines of

> Hello {{user}},
> 
> Its really important to keep your listed in CRM skills current and relevant. Remember to add to your list any new skills you may have acquired and remove any skills you think are no longer considered current. 
> 
> Please review the following lists. Note that skills highlighted are in demand.
> 
> ### Your Skills
> 1. Skill 1
> 2. **Skill 2**
> 3.  Skill 3
> 4. ...
> 9. Skill 9
> 
> ### Available Skills
> - **Skill A**
> - **Skill B**
> - **Skill C**
> - ...
> - Skill Z
> 
> To update your skills, click here.
> 
>

**Comment by JackDevAU** [comment]
Closing stale issue. 

Hey @drwharris 

1. Please reopen with detailed steps to action
