### ISSUE TITLE
🚰Filtering - Filter by consulting pages (only show skills that have consulting pages)

### ISSUE THREAD

**Issue by piers-sinclair** [SSWConsulting/SSW.People#373]
cc @ozdemir-mehmet, @leahy268 

Hi @drwharris ,

As per our conversation with @adamcogan @christianmorfordwaitessw @UlyssesMaclaren @calumjs @brydeno @JeanThirion SSW people skills includes a lot of skills that are not particularly relevant to our clients.

- [x] Update the filters to show only skills that have a link to a consulting page as per #365 

![image](https://user-images.githubusercontent.com/79821522/151749179-75f07cf9-2c0a-4f52-8cb3-4c8ba0621852.png)
**Figure: Too many skills - SSW People skills extend far down the page making it hard to navigate**

 

----- Update: 04/16/2024 -----
🎥 **V1 Done Video:** https://www.youtube.com/watch?v=t0Gc9cNHQhQ

----- Update: 28/04/2024 -----
🎥 **V2 Done Video:** https://www.youtube.com/watch?v=q8xGY2Yrk-g

---- Update: 07/05/2024 -----
🎥 **V3 Done Video:** https://www.youtube.com/watch?v=MmYW_LBBqjM

---- Update: 09/05/2024 -----
🎥 **V4 Done Video:** https://www.youtube.com/watch?v=GMXvuVomG_4

**Comment by JackDevAU** [comment]
CC @adamcogan @bradystroud @BrookJeynes 
Hey @pierssinclairssw 

This was implemented by @BrookJeynes but after people complained we have reverted it back to show rules without marketing pages again. 

1. Can we get a final, approval that this is the way we want skills to be displayed. 
2. If so, we will reimplement this feature and send an SSWALL email to let everyone know :)

**Comment by pierssinclairssw** [comment]
(checked by Jack P and Brook)
cc: @william-liebenberg 
As per my conversation with @UlyssesMaclaren @adamcogan @JackDevAU and @BrookJeynes 

This should not have been reverted. However, we did not communicate this change well enough to the company when it was made.

Hi @BrookJeynes 

We need to do the following to make sure people understand the change:

1. Film a Done Video showing how Consulting Services and Skills in CRM interact with SSW People and why it works that way.
2. Send out an SSWALL email letting everyone know what we have changed.

**Comment by Aibono1225** [comment]
Hi @piers-sinclair ,

> 1. Film a Done Video showing how Consulting Services and Skills in CRM interact with SSW People and why it works that way.

Done - please see https://www.youtube.com/watch?v=t0Gc9cNHQhQ

**Comment by piers-sinclair** [comment]
> Hi [@piers-sinclair](https://github.com/piers-sinclair) ,
> 
> > 1. Film a Done Video showing how Consulting Services and Skills in CRM interact with SSW People and why it works that way.
> 
> Done - please see https://www.youtube.com/watch?v=t0Gc9cNHQhQ

CC: @adamcogan 

(checked by @bradystroud)
Hi @Aibono1225 

I tried to call but couldn't get through.

Nice video but this is important to get right as we need the whole company to understand.

For that reason Test Fail

1. Please make a V2 including the below 3 feedback points.

Good Points
✅ Strong into
✅ Strong outro
✅ Good introduction of how the technologies list is very long (but I would scroll more to show the giant list)
✅ Nice and concise - great length

To Improve:

- Move camera lower (there's lots of space above your head)
- Fix the audio, it's not very good - try using Yeti mic and going in the recording room - there's lots of background noise. Get Ken or Sofie to check your setup.
- Pick a specific example of a skill that shows up and one that doesn't, and show it in CRM.
Here's what I would do

1. Show CRM | Skills | Apple Vision Pro
2. Point out it has no marketing page and no approver
3. Explain that these fields indicate whether this is something we want advertised to clients, and must be filled in for it to show up on SSW people.
4. Go to SSW People. Show that it doesn't show up in the list of skills on the left
5. Go to Matt Goldman's profile. Show that it doesn't show up in his skills.

Now what does a skill that does show up look like?

1. Show CRM | Skills | Blazor
2. Point out it has a marketing page of React
4. Explain what a marketing page is by going to CRM | Consulting Services | Blazor
5. Show how it has a Web Page URL and has been approved by Uly. That means it is live on our Website.
6. Navigate to https://www.ssw.com.au/consulting/blazor and show the page live
7. Navigate back to CRM | Skills | Blazor
8. Explain that it has Uly as an approver and that having both an approver and marketing page means it will show up on SSW People
9. Go to SSW People. Show that it does show up in the list of skills on the left
10. Go to Matt Goldman's profile. Show that it does show up in his skills.
11. Explain that it links to the marketing page.

**Comment by Aibono1225** [comment]
Hi @piers-sinclair ,

> 1. Please make a V2 including the below 3 feedback points.

Done - please check my v2 video: https://www.youtube.com/watch?v=q8xGY2Yrk-g

**Comment by piers-sinclair** [comment]
Hi @Aibono1225 

Thanks for this V2, looking awesome!

The headshot position and the audio is much better.

The explanation is also clearer

Two improvements I would have made are

- When you go to blazor as a skill open the page for Blazor itself.
- When you show Apple Vision Pro, show that it is missing from Matt Gs skills.

Regardless, I think people will understand the idea.

1. Please proceed with the SSWAll email and get it checked by Uly (including the video).

@bradystroud @UlyssesMaclaren @adamcogan 

1. Please watch the video when you have a min in case you think we need changes before sending an SSWAll email

**Comment by Aibono1225** [comment]
Update 07/05/2024:

🎥 v3 done video with some lower thirds added: https://www.youtube.com/watch?v=MmYW_LBBqjM

**Comment by Aibono1225** [comment]
Video Feedback from @BrookJeynes via email: Re: Rolling back on SSW People

> •	It would be nice to mention that the marketing page does not need to have the same name as the skill, i.e. angular could fit under the web apps marketing page
> •	I would have the video flow in such a way of:
>   a.	Here's what a skill is (on the people page)
>   b.	Here is what a marketing page is (on website)
>   c.	Here is how we represent skills behind the scenes (skill in CRM)
>   d.	For a skill to show, it needs to have a marketing page and be approved by someone
>   e.	Here is how to make a marketing page (this also needs to be approved by someone)
>   f.	With the marketing page now created, let's link it to our skill and get this approved by x
>   g.	With the skill approved and linked to a marketing page, we can see that it now shows up on a person's profile

  


To myself,

1. Record a v4

**Comment by Aibono1225** [comment]
Update 09/05/2024:

🎥 v4 done video: https://www.youtube.com/watch?v=GMXvuVomG_4

**Comment by Aibono1225** [comment]
> Please proceed with the SSWAll email and get it checked by Uly (including the video).

✨ Done - Email sent
Subject: SSW People - Skills are working differently between People and CRM
