### ISSUE TITLE
📄Report - Add a report to show all the skills that have been added in the last month (before and after)

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#374]
cc @ozdemir-mehmet, @leahy268 

Hi @drwharris ,

As per our conversation with @adamcogan @christianmorfordwaitessw @UlyssesMaclaren @calumjs @brydeno @JeanThirion SSW people skills has a lot of poor quality data. The problems include:

- Data Quality Control - The skills are not quality controlled meaning there is a lot of junk for example:
  - Duplication - There are skills that should be consolidated into one so the page is easier to navigate and people always add the same skill
e.g. (Blazor, BlazorServer, Blazers) or (SQL Server, Microsoft SQL Server)
  - Relevancy - There are a lot of skills that aren’t particularly relevant to our clients
e.g. C++, Copywriting, Skype for Business, Unity Engine etc
  - Scope - There are very vague skills which don’t give much information to a client
e.g. Support, Employee relations, Networking
  - Incorrect data - There are improperly named skills because anyone can add them
e.g. .NET EF Core exists but this is not a real skill, it should be just EF Core

This poor data affects the UX of SSW People because there are too many things to look through and the searching/filtering capability is compromised. For example, skill duplication means that when clients filter, they will miss people who haven’t added the alternative skills or the employees will need to add all alternatives polluting their profile with data.

![image](https://user-images.githubusercontent.com/79821522/151735489-12f19c74-b85d-4f9c-b54a-cc86ede1fcb0.png)
**Figure: Luke has been forced to add 3 different types of Blazor here, so clients filtering to Blazor can find him**

- [ ] Add a report to show all the skills that have been added in the last month (before and after)

**Comment by JackDevAU** [comment]
Closing stale issue. 

Hey @pierssinclairssw 

This issue seems to be a duplicate of https://github.com/SSWConsulting/SSW.People/issues/372 (which has been closed) 

1. Please reopen with the final solution
