### ISSUE TITLE
🐛 Profiles showing the wrong image

### ISSUE THREAD

**Issue by drwharris** [SSWConsulting/SSW.People#378]
CC @bradystroud @christianmorfordwaitessw 

I was asked to look into the wrong profile pictures being shown on the profiles page

![image](https://user-images.githubusercontent.com/19632724/152239568-4389ae77-bcbc-4f2c-b36e-a30a2606cd66.png)
Figure: Piers' picture is shown on Andrews card.

In this instance, reported by @PennyWalker, once she visited the incorrect profile and navigated back to the main profile page the problem was resolved.

In discussion with @pierssinclairssw he mentioned that he has seen this before as well. 

This is not something that has been reproducible on demand and there is suspicion that the issue is related to deployments and cache.

**Comment by AlexRothwell** [comment]
After the most recent deployment, the sorting of profiles does not seem to reliably apply to the images as well
![image](https://user-images.githubusercontent.com/7465195/207484029-83b9d83f-2905-4a1b-87d6-03c97da9d49f.png)
Figure: Only some profile images align with the profile

Those images that align with the profile seem to be just by chance as they are alphabetically first. It seems that the profiles are loaded alphabetically and then sorted, while the images remain in their initial position

**Comment by bradystroud** [comment]
@BrookJeynes IIRC you worked on this issue

How did you go?
Is there another PBI with your progress?

**Comment by JackDevAU** [comment]
Closing as this issue seems to be fixed.
