### ISSUE TITLE
CTA on the homepage + form in a separated page

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#382]
cc @UlyssesMaclaren @camillars @adamcogan @JeanThirion @pierssinclairssw 

Hey @christianmorfordwaitessw ,

On an SSW.People profile e.g. https://www.ssw.com.au/people/andrew-harris
We have a CTA button at the bottom that opens up a popup.

We want to add a similar CTA button at the top of the [homepage](https://www.ssw.com.au/people/).

Also... would it be possible to convert that popup form to open in a separated page with the form? (see reasons below from Camilla/Craig)

> ... but in my last chat with Craig, he mentioned in the future we should aim to get rid of the pop up forms we have as [it’s harder to track their performance and source](https://www.benchmarkemail.com/blog/online-forms-and-pop-up-forms/) (as we usually just have one form/URL for all pages e.g. thank you page) and then optimize it.  
I think it’s a good step if we can track results, so having a specific url for the form used in this page could be a good way of doing this.

1. Please add CTA as per screenshot below
2. Make the form this button opens to be in a separated page (e.g. https://www.ssw.com.au/people/book)

<img width="1046" alt="Screen Shot 2022-02-23 at 5 09 15 PM" src="https://user-images.githubusercontent.com/12601228/155437819-d5182889-d99e-4280-8135-290ad635c29c.png">

**Comment by tiagov8** [comment]
Hey @christianmorfordwaitessw 

Can we prioritize this one?

We want to make this button the homepage to point SSW People as soon as the new CTA is implemented:

<img width="1208" alt="Screen Shot 2022-03-29 at 5 13 26 PM" src="https://user-images.githubusercontent.com/12601228/160726290-f49c770f-3984-4152-99c7-6c323892b42a.png">

(and hopefully get rid of the ugly https://www.ssw.com.au/ssw/Consulting/Consulting.aspx )

**Comment by JackDevAU** [comment]
Hi @tiagov8 

Closing as this now uses the JOT form + we also have the "Contact Us" button in the MegaMenu :)
