### ISSUE TITLE
SSW.People alumni profiles' CTA needs to be different

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#389]
Hi team,

Currently any profile page, including former employees, have the same CTA section: "Interested in what XXX can do for you? ..."

It obviously doesn't make sense for alumni people (e.g. https://www.ssw.com.au/people/alumni/ivan-tyapkin)...

1. Please update the text for /alumni profiles from:

  > Interested in what XXX can do for you?
  Contact XXX's Account Manager to discuss your project

   to

  > Interested in what **SSW** can do for you?
  Contact **SSW**'s Account Manager to discuss your project

<img width="1283" alt="Screen Shot 2022-04-04 at 11 57 52 AM" src="https://user-images.githubusercontent.com/12601228/161613105-bc830560-51d1-4daf-82b6-b8d79af5a133.png">

**Comment by BrookJeynes** [comment]
Alumni pages now say "Interested in what we can do for you?" - https://www.ssw.com.au/people/alumni/damian-brady/

![Image](https://github.com/SSWConsulting/SSW.People/assets/25432120/72736a65-ab4f-4cc2-8f5b-0e4357701e2b)

**Comment by JackDevAU** [comment]
Hey @BrookJeynes 

> Interested in what SSW can do for you?
Contact **SSW's** Account Manager to discuss your project

Need to change the second line from <person> to SSW

**Comment by BrookJeynes** [comment]
Done - 

![Image](https://github.com/SSWConsulting/SSW.People/assets/25432120/0346fedc-7481-400d-a987-5c8ab7ae7e2c)
