### ISSUE TITLE
✨ Generate OpenGraph Preview

### ISSUE THREAD

**Issue by christoment** [SSWConsulting/SSW.People#402]
Hi SSW People team,

I was playing around with SSW People website and notice that we don't have a preview for our generated page.

Would be nice and looks more professional if we can have a preview link when copy-pasting a profile to a social media website 🙂.

1. Can we have an OpenGraph preview image in SSW People?

Preview on current SSW People:
https://www.opengraph.xyz/url/https%3A%2F%2Fwww.ssw.com.au%2Fpeople%2Fchris-clement/
![image](https://user-images.githubusercontent.com/35278147/173510269-f5860152-3bd6-413c-bbe9-837dae488de6.png)

Preview on GitHub repo page:
https://www.opengraph.xyz/url/https%3A%2F%2Fgithub.com%2Fchristoment%2Fjpeg-comparison/
![image](https://user-images.githubusercontent.com/35278147/173510314-fa087ac7-f352-47de-83cf-ef0cf64db6aa.png)

Preview on some other Gatsby SSG website:
https://www.opengraph.xyz/url/https%3A%2F%2Fwww.furbaby.rocks%2F/
![image](https://user-images.githubusercontent.com/35278147/173510649-74201d80-5f94-4278-a248-4b6fcadd4b54.png)

From the top of my head, looks like it will require to render an image for each profile change, and then store them in an asset bucket, and then put this URL in the `<meta>` tag. Need further investigation though.

**Comment by JackDevAU** [comment]
Hey @christoment 

Closing as this has been fixed! 

1. This is an awesome website though 😲😲 do we have a rule on it 😜

**Comment by christoment** [comment]
#522
