### ISSUE TITLE
✨ Add GitHub Skyline link

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.People#407]
GitHub have this cool Skyline feature that lets you view someone’s GitHub commits in 3D. Here is mine for 2021: https://skyline.github.com/matt-goldman/2021
 
As per my conversation with @adamcogan on Teams:
 
1.	Please add a link to everyone’s SSW People profile to their GitHub Skyline
 
The URL is skyline.github.com/[username]/[year] so you might be able to template this.

**Comment by JackDevAU** [comment]
Closing as Skyline seems to be broken at the moment. 

1. Please reopen when its working again
