### ISSUE TITLE
✨ Add "Copy Profile to Clipboard" feature

### ISSUE THREAD

**Issue by JeanThirion** [SSWConsulting/SSW.People#413]
Hey Team,

Account managers send emails to clients countless times a day, and we often send profiles as part of these emails.
e.g.:

> "Hi Bob Northwind,
> 
> Here are a couple profiles that would work for your project:
> 
> CALUM SIMPSON
> •	Profile: https://www.ssw.com.au/people/calum-simpson
> •	Title: Solution Architect
> •	Standard Hourly Rate: $305+GST
> •	Prepaid Hourly Rate: $290+GST (minimum 40 hours per resource, subject to prepaid terms)
> 
> ANDREW HARRIS
> •	Profile: https://www.ssw.com.au/people/andrew-harris
> •	Title: Solution Architect
> •	Standard Hourly Rate: $305+GST 
> •	Prepaid Hourly Rate: $290+GST (minimum 40 hours per resource, subject to prepaid terms)"

There is currently no way to generate this text and we have to manually craft it. I believe we have this info in SSW People already through CRM integration. 

1. Please add a button somewhere in profile page that copies this info in clipboard:
- Full Name
- Profile link
- Title
- Standard / Prepaid rate

2. Please investigate also adding the profile picture as part of the copy to clipboard (not sure if feasible)

**Comment by JeanThirion** [comment]
@pierssinclairssw any news on that? 😪

**Comment by pierssinclairssw** [comment]
> @pierssinclairssw any news on that? 😪

Not yet

**Comment by JackDevAU** [comment]
Closing this as we are moving the conversation over to this new issue: https://github.com/SSWConsulting/SSW.People/issues/507
