### ISSUE TITLE
🐛 BUG - /will URL giving an error - potential duplicated URL

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#418]
cc: @adamcogan, @christianmorfordwaitessw 

Hi @bradystroud ,

Trying to access https://www.ssw.com.au/people/will gives me an error:
<img width="779" alt="Screen Shot 2022-07-25 at 7 15 02 PM" src="https://user-images.githubusercontent.com/12601228/181066147-7a192bcd-051e-4e39-a828-97571aa7ec68.png">

--- 

I believe this is caused because somehow @william-liebenberg and @williamgreentreessw are both using the same URL:

<img width="703" alt="Screen Shot 2022-07-26 at 10 02 40 AM" src="https://user-images.githubusercontent.com/12601228/181067023-eb5e0286-ae27-43d2-a354-2c84c153754f.png">

**Figure: Google results point to Will L profile**

<img width="1001" alt="Screen Shot 2022-07-26 at 10 01 34 AM" src="https://user-images.githubusercontent.com/12601228/181067054-144786b0-3bc9-44e1-ae06-8486ed4e7476.png">

**Figure: SSW.People index point to Will G profile**

<img width="1492" alt="Screen Shot 2022-07-26 at 10 12 16 AM" src="https://user-images.githubusercontent.com/12601228/181069117-b7674da1-c870-4853-aec1-ecb5fe642d2c.png">

**Figure: Weirdly if you actually click from SSW.People index the URL does work and show Will G profile... however pasting on browser or clicking from somewhere else still shows the error from the 1st image**

---

1. Any idea why the page actually works when you click from SSW.People index? That's super odd!
2. Please investigate and fix the data for both Will's
3. Check if we can avoid this in the future (validating URLs)
4. Can we have a better error message from:
  "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
to
  "There are multiple resources pointing to the same URL. Being XXX and XXX"

**Comment by JackDevAU** [comment]
Closing as this has been fixed.
