### ISSUE TITLE
📧 Update email template

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.People#426]
Hey Team,

1. Make the following changes to the email
 
Change from

> Hi Tiago,
> 
> You have made a change to CRM | User | Adam
> These changes will appear in SSW People after 30 mins.
> Thanks for updating, it will be live soon
> 
> More information about this rolling build can be found here
> https://raw.githubusercontent.com/SSWConsulting/SSW.People.Profiles/main/.github/instructions/images/rolling_build.png
> 
> -- Powered By CRM.SSWPeople
> 

To

> Hi Tiago,
> 
> Thanks for your updates to [SSW People | Adam](https://www.ssw.com.au/people/adam-cogan). These changes will be live after about 30 mins.
> 
> This happened because you made a change to [CRM | User | Adam](https://ssw.crm6.dynamics.com). More information about this rolling build can be found here
> https://raw.githubusercontent.com/SSWConsulting/SSW.People.Profiles/main/.github/instructions/images/rolling_build.png
> 
> -- Powered By CRM.SSWPeople
>            https://github.com/SSWConsulting/SSW.People  (an open source project by [www.ssw.com.au](http://www.ssw.com.au/) )

**Comment by JackDevAU** [comment]
Closing as this has been implemented.
