### ISSUE TITLE
✨ Make former alumni links "/alumni/" to redirect to active employee link

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#432]
Hi team,

We have the case where Will L left and then returned to SSW

After leaving his profile was https://www.ssw.com.au/people/alumni/william-liebenberg 
Once he's returned that link is giving a 404. 

Ideally it should redirect to https://www.ssw.com.au/people/william-liebenberg

1. Could we automatically make former employees who return to SSW links to redirect?
2. If not, can we manually do this for Will L?

Cheers,

**Comment by Aibono1225** [comment]
Hi @tiagov8 ,

> 1. Could we automatically make former employees who return to SSW links to redirect?

At the code level, we currently can't tell if an employee has previously left SSW. So there isn't an efficient way to automatically redirect the wrong links for these employees.

> 2. If not, can we manually do this for Will L?

We could manually create redirects for each of them. But I'm thinking it would be easier to just directly modify the links wherever they are used (e.g. Rules.Content) 🤔


### Option A: Create a json file in SSW.People and add custom redirects:
```
{
    "fromPath": "/alumni/william-liebenberg",
    "toPath": "/william-liebenberg/"
  },
```

### Option B: At the place where we use a former link (for example Rules.Content), replace it with the correct one (we should have already done this for William 😉)


Please let me know your thought on this.

**Comment by tiagov8** [comment]
Hi @Aibono1225 

I guess B. 

- [ ] Please action
