### ISSUE TITLE
✨ Make the Others category in the location filter more specific

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.People#443]
Hi Team

As per conversation with @adamcogan, we'd like to add this new feature.
  
### Pain

The Others category in the location filter is quite ambiguous. We can’t tell the location of the people in the Others category unless we go to the detailed profile.

### Suggested Solution

We can make it more specific by changing the Others button into a dropdown and it can have 4 options:
- Others (Default)
- China
- France
- Remote

### Screenshots

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/37203901/201879310-2b38997c-305d-4bfb-b2c9-aff11546cb52.png">

**Figure: Original**

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/37203901/201879457-478fd2b1-02aa-41a4-b3a3-528f4828da8e.png">

**Figure: Mockup**

Thanks!

**Comment by JackDevAU** [comment]
Closing as this has been superseded by https://github.com/SSWConsulting/SSW.People/issues/449
