### ISSUE TITLE
✨ Show office link after choosing a location

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.People#444]
Cc: @adamcogan 

Hi @2fernandez 
  
### Pain

After we choose a location, we'd like to see the office link under it. 

### More Information

Instead of the raw link, we can show a nicer text, e.g. Our Office in Sydney

### Screenshots
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/37203901/201889339-a50f1fef-5f68-478a-814b-72d5ca166c9d.png">

Thanks!

**Comment by JackDevAU** [comment]
Closing stale issue. 

1. Please reopen if you would like this feature
