### ISSUE TITLE
SSW Website | Add all fuzzy and exact matching for pages in SkillUrlData.json 

### ISSUE THREAD

**Issue by ozairashfaqueSSW** [SSWConsulting/SSW.People#446]
As per my conversation with @adamcogan

1. Add exact and fuzzy keywords for all consulting pages
![image](https://user-images.githubusercontent.com/96504411/202325493-50947835-b0ef-41c6-aefe-600360a235f3.png)
**Figure: The highlight has neither exact or fuzzy match**

**Comment by JackDevAU** [comment]
Closing as https://github.com/SSWConsulting/SSW.People/issues/496 supersede it
