### ISSUE TITLE
♻️ Update footer social icons

### ISSUE THREAD

**Issue by 2fernandez** [SSWConsulting/SSW.People#447]
Cc: @jaydenalchin, @hveraus, @Geordie88 
Hi @tiagov8, 

### Tasks

- [x] Remove WeChat social media icon.
- [x] Add TikTok

**Comment by jaydenalchin** [comment]
@2fernandez @tiagov8 

Should this mention replacing with TikTok icon?

**Comment by 2fernandez** [comment]
> @2fernandez @tiagov8
> 
> Should this mention replacing with TikTok icon?

Done! updated the original task.

**Comment by JackDevAU** [comment]
Hi Team, 

As per my conversation with @jaydenalchin

1. Change social links and icons to match SSW Rules footer.

**Comment by BrookJeynes** [comment]
Closing this as it's now done.

![image](https://github.com/SSWConsulting/SSW.People/assets/25432120/4334663f-acfa-4a61-b650-0ba9ce4d0cd8)
ssw.com.au/people
