### ISSUE TITLE
🐛 China redirect not working

### ISSUE THREAD

**Issue by BrookJeynes** [SSWConsulting/SSW.People#451]
Cc: @bradystroud 

Hi Team

### Describe the Bug

There are two SSW.People sites, Chinese and English. The English site is supposed to detect whether your IP is China based, and if so, redirect you to the correct site however, this is not working.

The code is currently commented out here: https://github.com/SSWConsulting/SSW.People/pull/450/files#

### To Reproduce
1. Go to https://www.ssw.com.au/people/
2. Click on network tab in dev tools
3. Scroll down to unresolved request "GET https://api.userinfo.io/userinfos"
4. See error "An error occurred: | SEC_ERROR_EXPIRED_CERTIFICATE"

### Expected Behavior

When a China based IP navigates to the SSW.People site they are redirected to the Chinese site.

### Tasks
- [ ] Investigate
- [ ] Fix

### Environment
 - Device: Macbook
 - Browser: Chrome and Firefox
 - OS: MacOS

### Screenshots

![image](https://user-images.githubusercontent.com/25432120/204438182-21c4c45a-ce42-4953-8fe7-1a5473028f9f.png)

Thanks!

**Comment by JackDevAU** [comment]
Hi @BrookJeynes, 

Closing this 

1. Please reopen if this is still an issue
