### ISSUE TITLE
SSW People Profile - bug with skills not being updated

### ISSUE THREAD

**Issue by KristenHu** [SSWConsulting/SSW.People#462]
Hi @bradystroud ,

The skills in my SSW People profile were not updated after the skills list in CRM was changed.

- [ ] please fix it

![](https://user-images.githubusercontent.com/52522913/208568840-92e3fb65-8d28-48aa-89b5-f628b5a95c25.png)
**Figure: My SSW People Profile**
![](https://user-images.githubusercontent.com/52522913/208568904-81568087-cb0e-4309-9f73-4c5330584238.png)
**Figure: My CRM skill Page**

**Comment by bradystroud** [comment]
Cc @christianmorfordwaitessw

**Comment by JackDevAU** [comment]
Hi @KristenHu 

Closing as this seems to have been fixed. 

FYI - "Keen to learn" doesn't show up on People. 

Please reopen if this issue happens again :)
