### ISSUE TITLE
BUG - GitHub Contributions not displaying

### ISSUE THREAD

**Issue by christianmorfordwaitessw** [SSWConsulting/SSW.People#465]
cc: @adamcogan 

Hi Team,

The GitHub Contributions Calendar is not working. This appears to be an issue for all installations using the package.
As the demo page is also showing an error when trying to render the calendar, it is likely that the package is having trouble scraping the HTML from the GitHub user profile. Similar Issue: https://github.com/grubersjoe/react-github-calendar/issues/25

![image](https://user-images.githubusercontent.com/56522256/210946503-5d3e2218-845f-4478-9ba6-102a517dea71.png)
**Figure: GitHub Contributions Calendar not working on SSW.People**

![image](https://user-images.githubusercontent.com/56522256/210946847-17d8d50d-1883-4bc8-be2c-877d4892874b.png)
**Figure: Contributions Calendar not working on demo site - https://grubersjoe.github.io/react-github-calendar/**

**Comment by BrookJeynes** [comment]
CC: @bradystroud 

Hey @christianmorfordwaitessw,

This was fixed here: https://github.com/SSWConsulting/SSW.People/issues/433
