### ISSUE TITLE
SSW.People - Some profiles are not being indexed by Google

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#467]
cc @GordonBeeming @adamcogan @billyterblanche 

Hi @bradystroud 

Please investigate why some SSW People profiles are not being indexed by Google
 
Here are some example searches where profiles are indexed vs not indexed
✅ [site:ssw.com.au/people/ Adam - Google Search](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com.au%2Fsearch%3Fq%3Dsite%253Assw.com.au%252Fpeople%252F%2BAdam%26ei%3DZbO-Y8vdAoz4gQbiv5q4Bg%26ved%3D0ahUKEwiLpOLmyb_8AhUMfMAKHeKfBmcQ4dUDCA8%26uact%3D5%26oq%3Dsite%253Assw.com.au%252Fpeople%252F%2BAdam%26gs_lcp%3DCgxnd3Mtd2l6LXNlcnAQA0oECEEYAUoECEYYAFD9A1j0CGDYCmgCcAB4AIAB3QKIAc0GkgEFMi0yLjGYAQCgAQHAAQE%26sclient%3Dgws-wiz-serp&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C4b8a38a509224e61757b08daf3e1ba4c%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638090448071561066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EFNfYA4IieP7Wx92ya9J9CArtPQVj55fNQZDHWLbma0%3D&reserved=0)
✅ [site:ssw.com.au/people/ Tiago - Google Search](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com.au%2Fsearch%3Fq%3Dsite%253Assw.com.au%252Fpeople%252F%2BTiago%26ei%3DbrO-Y7_VIc2qgAbSyoCQDQ%26ved%3D0ahUKEwi_xKbryb_8AhVNFcAKHVIlANIQ4dUDCA8%26uact%3D5%26oq%3Dsite%253Assw.com.au%252Fpeople%252F%2BTiago%26gs_lcp%3DCgxnd3Mtd2l6LXNlcnAQA0oECEEYAUoECEYYAFCHBVjQCWDSC2gCcAB4AIAB4AGIAacIkgEDMi01mAEAoAEBwAEB%26sclient%3Dgws-wiz-serp&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C4b8a38a509224e61757b08daf3e1ba4c%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638090448071561066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WJLt7QTr1rQUKo59ci4NqW3P%2FOAbv0DOO5T0mjOPWj8%3D&reserved=0)
✅ [site:ssw.com.au/people/ Hugo - Google Search](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com.au%2Fsearch%3Fq%3Dsite%253Assw.com.au%252Fpeople%252F%2BHugo%26ei%3DvLO-Y9mTF4WYgQbvyb2oCw%26ved%3D0ahUKEwjZ4bSQyr_8AhUFTMAKHe9kD7UQ4dUDCA8%26uact%3D5%26oq%3Dsite%253Assw.com.au%252Fpeople%252F%2BHugo%26gs_lcp%3DCgxnd3Mtd2l6LXNlcnAQA0oECEEYAUoECEYYAFDvB1jtC2DuDWgCcAB4AIAB2wKIAb0IkgEFMi0zLjGYAQCgAQHAAQE%26sclient%3Dgws-wiz-serp&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C4b8a38a509224e61757b08daf3e1ba4c%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638090448071561066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xaVvc67nDAVS9IDag3dxNlwdhZW4CVE0Dm9JhTGFg%2F0%3D&reserved=0)
❌ [site:ssw.com.au/people/ Gordon - Google Search](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com.au%2Fsearch%3Fq%3Dsite%253Assw.com.au%252Fpeople%252F%2BGordon%26ei%3DjbO-Y6iTLduBhbIPjeeSIA%26ved%3D0ahUKEwjojZb6yb_8AhXbQEEAHY2zBAQQ4dUDCA8%26uact%3D5%26oq%3Dsite%253Assw.com.au%252Fpeople%252F%2BGordon%26gs_lcp%3DCgxnd3Mtd2l6LXNlcnAQA0oECEEYAUoECEYYAFD0BVjUCmCHDWgCcAB4AIABgAKIAbIKkgEDMi02mAEAoAEBwAEB%26sclient%3Dgws-wiz-serp&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C4b8a38a509224e61757b08daf3e1ba4c%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638090448071561066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X0PG8HI02EKTSFdVXb8WFhlafIqNXOWhYPHNbOAXSAc%3D&reserved=0) (shows Gordon Harley but not my profile)
❌ [site:ssw.com.au/people/ Billy - Google Search](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com.au%2Fsearch%3Fq%3Dsite%253Assw.com.au%252Fpeople%252F%2BBilly%26ei%3DQLO-Y7KsGoGTgQaE-4ywCQ%26ved%3D0ahUKEwiyzKfVyb_8AhWBScAKHYQ9A5YQ4dUDCA8%26uact%3D5%26oq%3Dsite%253Assw.com.au%252Fpeople%252F%2BBilly%26gs_lcp%3DCgxnd3Mtd2l6LXNlcnAQA0oECEEYAUoECEYYAFDlelijjgFgyJEBaANwAHgAgAGGAogBrQmSAQMyLTWYAQCgAQHAAQE%26sclient%3Dgws-wiz-serp&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C4b8a38a509224e61757b08daf3e1ba4c%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638090448071561066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rNVJyNFA7zt9bbwHsWRFyyvCDXN62SBdRNxS%2BVVXjag%3D&reserved=0)
❌ [site:ssw.com.au/people/ Levi - Google Search](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com.au%2Fsearch%3Fq%3Dsite%253Assw.com.au%252Fpeople%252F%2BLevi%26ei%3DWbO-Y43hE5akgQbhqam4BA%26ved%3D0ahUKEwjN8Zbhyb_8AhUWUsAKHeFUCkcQ4dUDCA8%26uact%3D5%26oq%3Dsite%253Assw.com.au%252Fpeople%252F%2BLevi%26gs_lcp%3DCgxnd3Mtd2l6LXNlcnAQA0oECEEYAUoECEYYAFDDBli_CmCzDGgCcAB4AIABnQKIAb8FkgEDMi0zmAEAoAEBwAEB%26sclient%3Dgws-wiz-serp&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C4b8a38a509224e61757b08daf3e1ba4c%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638090448071561066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2S9zXmvlQITcDawV2Xce4oCZAbX%2BY09vd4zhoapAbI0%3D&reserved=0)

**Comment by bradystroud** [comment]
Hi @tiagov8 @GordonBeeming 

I checked out Gordon's page on Google Search Console and there was no issues, but it hasn't been indexed yet.

![image](https://user-images.githubusercontent.com/38869720/211936664-89ccf1dc-ef1a-4efe-a8a4-aff5b0058daa.png)
**Figure: No issues with Gordons page**

I also noticed that the generated [sitemap for SSW.People](https://www.ssw.com.au/people/sitemap/sitemap-0.xml) had not been submitted to the Google Search Console. After adding it, it discovered 257 URLs to crawl and index.

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/38869720/211942316-8a2cd2f1-0339-414f-8e01-98c6edb43a8c.png">
 
Hopefully adding the sitemap will allow the Google to discover SSW.People pages.

I will come back to this issue in a month to ensure that these pages were indexed.

**Comment by bradystroud** [comment]
I found that the `robots.txt` file has the wrong URL for the sitemap.

https://github.com/SSWConsulting/SSW.People/blob/82317b09344165f844cb25e27c72e36631a5f1d3/static/robots.txt#L2

This has been fixed in PR #468

**Comment by JackDevAU** [comment]
Closing as the following have been indexed correctly! 

~~❌~~ ✅ [site:ssw.com.au/people/ Gordon - Google Search](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com.au%2Fsearch%3Fq%3Dsite%253Assw.com.au%252Fpeople%252F%2BGordon%26ei%3DjbO-Y6iTLduBhbIPjeeSIA%26ved%3D0ahUKEwjojZb6yb_8AhXbQEEAHY2zBAQQ4dUDCA8%26uact%3D5%26oq%3Dsite%253Assw.com.au%252Fpeople%252F%2BGordon%26gs_lcp%3DCgxnd3Mtd2l6LXNlcnAQA0oECEEYAUoECEYYAFD0BVjUCmCHDWgCcAB4AIABgAKIAbIKkgEDMi02mAEAoAEBwAEB%26sclient%3Dgws-wiz-serp&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C4b8a38a509224e61757b08daf3e1ba4c%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638090448071561066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X0PG8HI02EKTSFdVXb8WFhlafIqNXOWhYPHNbOAXSAc%3D&reserved=0) (shows Gordon Harley but not my profile)
~~❌~~ ✅ [site:ssw.com.au/people/ Billy - Google Search](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com.au%2Fsearch%3Fq%3Dsite%253Assw.com.au%252Fpeople%252F%2BBilly%26ei%3DQLO-Y7KsGoGTgQaE-4ywCQ%26ved%3D0ahUKEwiyzKfVyb_8AhWBScAKHYQ9A5YQ4dUDCA8%26uact%3D5%26oq%3Dsite%253Assw.com.au%252Fpeople%252F%2BBilly%26gs_lcp%3DCgxnd3Mtd2l6LXNlcnAQA0oECEEYAUoECEYYAFDlelijjgFgyJEBaANwAHgAgAGGAogBrQmSAQMyLTWYAQCgAQHAAQE%26sclient%3Dgws-wiz-serp&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C4b8a38a509224e61757b08daf3e1ba4c%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638090448071561066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rNVJyNFA7zt9bbwHsWRFyyvCDXN62SBdRNxS%2BVVXjag%3D&reserved=0)
~~❌~~ ✅ [site:ssw.com.au/people/ Levi - Google Search](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com.au%2Fsearch%3Fq%3Dsite%253Assw.com.au%252Fpeople%252F%2BLevi%26ei%3DWbO-Y43hE5akgQbhqam4BA%26ved%3D0ahUKEwjN8Zbhyb_8AhUWUsAKHeFUCkcQ4dUDCA8%26uact%3D5%26oq%3Dsite%253Assw.com.au%252Fpeople%252F%2BLevi%26gs_lcp%3DCgxnd3Mtd2l6LXNlcnAQA0oECEEYAUoECEYYAFDDBli_CmCzDGgCcAB4AIABnQKIAb8FkgEDMi0zmAEAoAEBwAEB%26sclient%3Dgws-wiz-serp&data=05%7C01%7CTiagoAraujo%40ssw.com.au%7C4b8a38a509224e61757b08daf3e1ba4c%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638090448071561066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2S9zXmvlQITcDawV2Xce4oCZAbX%2BY09vd4zhoapAbI0%3D&reserved=0)
