### ISSUE TITLE
🐛 Skills list doesn't include Power Apps

### ISSUE THREAD

**Issue by SamBWagner** [SSWConsulting/SSW.People#469]
In the list on the left, there is no Power Apps

https://github.com/SSWConsulting/SSW.People/issues/469#tasklist-block-dd979c67-fc7b-484e-b054-8f14b7ae34c6

![image](https://user-images.githubusercontent.com/66365977/213595497-63d39f75-a8d9-47fc-98ae-f641fdf96243.png)
**Figure: SSW People | No PowerApps in the list. SSW CRM | PowerApps is in the list**

**Comment by JackDevAU** [comment]
Closing as PowerApps has been added. 

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/98ae0991-57fb-4028-bcbf-866d7d65984e)
![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/725f3d61-6d99-4a5e-a656-5bfc6b50e00d)
**Figure: PowerApps in the list + page**
