### ISSUE TITLE
🐛 BUG - Github contributions not showing on profile

### ISSUE THREAD

**Issue by PothieuG** [SSWConsulting/SSW.People#477]
As per my conversatio with @tiagov8 and @bradystroud  :

Following an item in my induction regarding the creation of my SSW profile, Tiago mentioned to me that my Github Contributions do not appear on his end (desktop and mobile), whereas I, Hugo, and Jean do not seem to have the same issue.

To reproduce : Just check on my profile [https://ssw.com.au/people/gilles-pothieu](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fssw.com.au%2Fpeople%2Fgilles-pothieu&data=05%7C01%7CGillesPothieu%40ssw.fr%7Cd059e45f503045c91dde08db295ccb07%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638149250713139342%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pQaO3xLsfBZD1zzCjd8nU0HmtP3i6dShCn5i6M8ITMU%3D&reserved=0](https://ssw.com.au/people/gilles-pothieu)) if my Github Contributions are showing up.

```[tasklist]
### Tasks
- [ ] Make investigations why this is happening only on Tiago’s end
- [ ] If the source of the problem is found, fix it.
```

<img width="1727" alt="Gilles's profile on Tiago's computer" src="https://user-images.githubusercontent.com/45673557/226575010-6f83e87b-da4f-4fe3-9617-e43474e65b94.png">
  
**Figure : Gilles's profile on Tiago's computer**

**Comment by JackDevAU** [comment]
Closing - as this seems to be working again. 

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/7d4bc0f6-dd9e-4cdf-a447-df65090e9f1b)
**Figure GitHub contributions are back!**
