### ISSUE TITLE
🔗 Broken link - manifest.json

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#480]
cc @wicksipedia @adamcogan @chrisschultzssw 

Hi @bradystroud,

CodeAuditor caught this broken link on SSW.People website: https://www.ssw.com.au/people/manifest.json

1. Please fix

<img width="1288" alt="Screenshot 2023-04-24 at 2 44 13 PM" src="https://user-images.githubusercontent.com/12601228/234076290-4917df86-dd65-4784-9d45-e7662d00d185.png">

Cheers,

**Comment by tiagov8** [comment]
cc @tombui99 

Hey @bradystroud 

FYI - This is preventing us from getting CodeAuditor to 0:
https://codeauditor.com/build/f8991fb0-9694-4db4-c10e-76903cef833a

**Comment by bradystroud** [comment]
Hey @tiagov8 

> 1. Please fix

Done - https://ssw.com.au/people/manifest.json
