### ISSUE TITLE
🐛 BUG - Profiles do not redirect to alumni if there is no slash "/" at the end

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#500]
cc @adamcogan @bradystroud 

-- 

Hi @BrookJeynes , 

On [this page](https://www.ssw.com.au/ssw/Testimonials/default.aspx) there is a link to https://www.ssw.com.au/people/rebecca-liu
**It gives a 404!**

The same error happens in the same page for this profile: https://www.ssw.com.au/people/andreas-lengkeek

Only if you add a slash at the end 
https://www.ssw.com.au/people/rebecca-liu/ 
the URL correctly redirects to 
https://www.ssw.com.au/people/alumni/rebecca-liu/

- [x] Please make sure URLs without the slash will also redirect correctly

<img width="1051" alt="Screenshot 2023-07-20 at 3 07 03 PM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/1b7f96b2-eed5-43c0-a77e-059a34addb24">

**Figure: We shouldn't get a 404 from this link :/**

<img width="1237" alt="Screenshot 2023-07-20 at 3 15 45 PM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/94cbad8f-7118-4d98-a9ae-f7169deb0bf2">

**Figure: https://codeauditor.com/build/e9b1aeac-9e52-4997-d09a-e3ac80562db2 report**

**Comment by JackDevAU** [comment]
Closing as this issue has been fixed - https://github.com/SSWConsulting/SSW.People/pull/538

**Comment by tiagov8** [comment]
cc @adamcogan @pierssinclairssw 

Hi @JackDevAU 

@jontygardner reported this broken link today: https://www.ssw.com.au/people/toby-goodman

I think it is related to this task so I am reopening

**Comment by jontygardner** [comment]
Hey Tiago,

I got to this page by clicking on Toby Goodman as an author for a Rules page. I don't remember which Rules Page exactly. 
 
![Uploading image.png…]()
 
1.	Broken link – please fix

**Comment by JackDevAU** [comment]
Hey @jontygardner & @tiagov8 

This is a bigger issue - toby doesn't have a page created for him at all :O 

Hi Myself,

- [ ] Investigate the issue

**Comment by JackDevAU** [comment]
Reclosing this issue as it's unrelated to the Toby issue. 
View the toby issue here: https://github.com/SSWConsulting/SSW.People/issues/554
