### ISSUE TITLE
✨ New feature - Copy the person’s information to the clipboard 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#507]
cc @UlyssesMaclaren 

Based on email: **RE: Initial Meeting - I see a wall of text** by Hashem and Uly

Hi team,
 
Please add another button beside the download button on the SSW people profile pic. It will copy the person’s information to the clipboard into a format as such:
 
(feel free to tweak this to look better… maybe a square image?)
  
> ![image](https://github.com/SSWConsulting/SSW.People/assets/12601228/7b0c475e-0404-46e5-92a1-b912e8061ad8)
> Andrew Harris
> Profile: https://www.ssw.com.au/people/andrew-harris
> Standard Hourly Rate: $285+GST
> Prepaid Hourly Rate: $270+GST (minimum 40 hours per resource, subject to prepaid terms)

 
A user would then be able to paste this information in a Word document or such.
 
An example of where the button would ideally go:
 
![image](https://github.com/SSWConsulting/SSW.People/assets/12601228/e40463f6-4e6b-40c7-b6c1-7227e788e6b5)
 
**Figure: Potential ‘copy to clipboard’ button location**

**Comment by UlyssesMaclaren** [comment]
+1 for option 3











Ulysses Maclaren   |   SSW General Manager<http://www.ssw.com.au/People/Ulysses-Maclaren?utm_source=emailsignature>   |    +61 419 418 232<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

**Comment by JackDevAU** [comment]
As per my conversation with @JeanThirion, @UlyssesMaclaren and @PennyWalker. The formatting should be more compact. 

From:

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/bfb05918-c455-4a28-a2dc-d22af61cbbc7)


To: 

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/95ffc5c8-3291-48b1-b069-05184df5231b)


To Myself, 

1. Implement the compact new design

**Comment by UlyssesMaclaren** [comment]
Small thing… the prepaid rate there is wrong. Should be a $15 discount











Ulysses Maclaren   |   SSW General Manager<http://www.ssw.com.au/People/Ulysses-Maclaren?utm_source=emailsignature>   |    +61 419 418 232<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

**Comment by JackDevAU** [comment]
> Small thing… the prepaid rate there is wrong. Should be a $15 discount

Good spot 😅 I'll fix that as well :)

**Comment by JeanThirion** [comment]
ONE FULL YEAR after I requested this, it's AWESOME to see it come to life ! Thank you <3

**Comment by JackDevAU** [comment]
Done - 

I've adjusted the discount to 15 and have changed to the new format. 

1. Please give feedback or react to this message if it is perfect 🚀

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/e214f5ad-7b04-4751-9934-3d4335ec1279)
**Figure: New Format pasted into Outlook**

**Comment by bradystroud** [comment]
@JeanThirion @UlyssesMaclaren @PennyWalker 
Tip - you can test it out on staging https://staging.ssw.com.au/people/brady-stroud/

**Comment by UlyssesMaclaren** [comment]
Hey Jack,

The image didn’t seem to copy:

[A close-up of a computer code  Description automatically generated]











Ulysses Maclaren   |   SSW General Manager<http://www.ssw.com.au/People/Ulysses-Maclaren?utm_source=emailsignature>   |    +61 419 418 232<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

**Comment by JeanThirion** [comment]
Hey Brady,

Works great but same as Uly – pictures not working ☹



Resources

[Jean Thirion's profile picture]
Jean Thirion

  *   Profile: https://ssw.com.au/people/jean-thirion
  *   Standard Hourly Rate: $325+GST
  *   Prepaid Hourly Rate: $310+GST (minimum 40 hours per resource, subject to prepaid terms)

[Ulysses Maclaren's profile picture]
Ulysses Maclaren

  *   Profile: https://ssw.com.au/people/uly
  *   Standard Hourly Rate: $225+GST
  *   Prepaid Hourly Rate: $210+GST (minimum 40 hours per resource, subject to prepaid terms)

[Hugo Pernet's profile picture]
Hugo Pernet

  *   Profile: https://ssw.com.au/people/hugo-pernet
  *   Standard Hourly Rate: $325+GST
  *   Prepaid Hourly Rate: $310+GST (minimum 40 hours per resource, subject to prepaid terms)













Jean Thirion   |   SSW France CEO + Solution Architect<http://www.ssw.com.au/People/Jean-Thirion?utm_source=emailsignature>   |    +61 402 924 179<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

**Comment by tiagov8** [comment]
Hey @JackDevAU 

The image didn't work for me either... there was a all white image in its place:

> <img width="708" alt="Screenshot 2023-08-21 at 11 36 37 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/dc899a92-ea3c-4c89-9bb2-045a843d80bc">

---

Mu suggestion:

1. Less is more and DRY - Change from:

> **Brady Stroud** 
> - Profile: https://ssw.com.au/people/brady-stroud 
> - Standard Hourly Rate: $265+GST 
> - Prepaid Hourly Rate: $250+GST (minimum 40 hours per resource, subject to prepaid terms)

to

> **BRADY STROUD** | https://ssw.com.au/people/brady-stroud 
> Hourly Rates: 
> - Standard: $265+GST 
> - Prepaid: $250+GST (minimum 40h, subject to [prepaid terms](https://ssw.com.au/terms-and-conditions))

**Comment by JackDevAU** [comment]
Hi @JeanThirion, @UlyssesMaclaren, @PennyWalker @tiagov8 

A fix has been pushed to staging and is now ready to be tested again 🚀

1. Please "test please" [staging.ssw.com.au/people/brady-stroud](https://staging.ssw.com.au/people/brady-stroud/)

Should get the following: 

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/e8ac8ce1-4e21-4684-a6c4-ebe61c21ee85)
**Figure: Brady's info copied into an Outlook email**

**Comment by UlyssesMaclaren** [comment]
Test passed











Ulysses Maclaren   |   SSW General Manager<http://www.ssw.com.au/People/Ulysses-Maclaren?utm_source=emailsignature>   |    +61 419 418 232<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

**Comment by PennyWalker** [comment]
Test passed :)











Penny Walker   |   SSW QLD State + International Manager<http://www.ssw.com.au/People/Penny-Walker?utm_source=emailsignature>   |    +61 415 759 348<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

**Comment by JeanThirion** [comment]
[Brady Stroud's profile picture]
Brady Stroud | ssw.com.au/people/brady-stroud<https://ssw.com.au/people/brady-stroud>
Hourly Rates:

  *   Standard: $265+GST
  *   Prepaid: $250+GST (minimum 40h, subject to prepaid terms<https://ssw.com.au/terms-and-conditions>)


For the record I don’t like the link right next to the name, I think the whole rectangle of information looks messier although more compact.

Otherwise test passed











Jean Thirion   |   SSW France CEO + Solution Architect<http://www.ssw.com.au/People/Jean-Thirion?utm_source=emailsignature>   |    +61 402 924 179<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

**Comment by JackDevAU** [comment]
Done - https://youtu.be/vqgMX13Pk8g

**Comment by tiagov8** [comment]
**Note:** A new suggestion was created based on this Issue: https://bettersoftwaresuggestions.com/github/help-me-have-a-clean-message-when-replying-to-an-issue-via-email/
