### ISSUE TITLE
♻️ Add/Update Open Graph image for SSW.People

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#522]
cc @Geordie88 @camillars 

### Hi team, 

- [x] 1. Add/Update Open Graph for SSW.People https://www.ssw.com.au/people/ with this image:
  [Open-Graph-images-Website-People.jpg](https://sswcom.sharepoint.com/:i:/r/sites/SSWDESIGN/Shared%20Documents/General/Project-SSWWebsite/Open-Graph-Images/Open-Graph-images-Website-People.jpg)

- [x] 2. Test on a tool like https://robolly.com/open-graph-preview

as per https://www.ssw.com.au/rules/use-open-graph/ 

---

Related to https://github.com/SSWConsulting/SSW.Rules/issues/1085

**Comment by Aibono1225** [comment]
⭐ Done

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/78efd606-fbd8-4abc-8e95-e3464930c6ee)
