### ISSUE TITLE
💸 Tech Debt - Update SSW.Megamenu

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.People#532]
cc @bradystroud 
As per https://github.com/SSWConsulting/SSW.Website/issues/1357, the SSW.Megamenu package has been upgraded. 

```[tasklist]
### Tasks
- [x] Upgrade SSW.Megamenu to 3.2.2
- [x] Test on staging
```

**Comment by BrookJeynes** [comment]
Done - SSW.People now uses version 3.2.3 (latest at current time)
