### ISSUE TITLE
🐛BUG - MOBILE - Edit | Info buttons + contact box not formatting correctly

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.People#544]
CC @adamcogan @tiagov8 @bradystroud @jakebayliss @BrookJeynes @jaydenalchin 

Hi Team, 

### Issue 

The mobile responsiveness of a person's profile needs some more spacing. 
The content seems to align to the left and the spacing between items doesn't seem to be working correctly. (see image below) 

### Tasks

- [ ] Investigate why this is happening every so often 
- [ ] Fix the mobile responsiveness issue 

### Acceptance Criteria 

1. Nothing is misaligned. 
2. Photo and contact box are spaced evenly.
3. Info | edit buttons are right aligned 

### Screenshots 

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/5f3e8c95-d73c-47cd-98e5-a84ddc9d9f8c)
**Figure: Jake's profile formatting left aligned?**

**Comment by JackDevAU** [comment]
Hi @adamcogan, @jaydenalchin and @tiagov8 

Here are some options, I quickly edited. Should we make the mobile responsiveness behave like any of the following? 


![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/07852a12-b2a3-4fc9-a2b5-de53d3f03df8)
**Figure: 1**

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/68bb01e1-2b8c-4571-b827-d8c4f8582b7c)
**Figure: 2**

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/a3d66239-5c4d-47f7-b3f2-3432ce79a72d)
**Figure: 3**

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/7d313468-92d8-4f32-b3f7-33e2742bc927)
**Figure: 4**

**Comment by tiagov8** [comment]
Hi @JackDevAU 

**Figure 1** is the way to go

- [ ] Please action

**Comment by JackDevAU** [comment]
Hey @tiagov8 

1. Please "test please" 
https://staging.ssw.com.au/people/jake-bayliss/

**Comment by tiagov8** [comment]
Hi @JackDevAU 

Test fail ❌
We need more padding where the red line is below

- [ ] 1. Please action

<img width="497" alt="Screenshot 2023-10-19 at 1 18 01 PM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/5b89ab62-e421-47e3-bdfe-458bd3da1630">

**Comment by JackDevAU** [comment]
Hey @tiagov8 

> 1. Please action

Done - Added padding 1rem (same distance from the quote below) 

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/ee38cf0b-6d36-4967-baab-4c270e7cf105)
**Figure: added padding**

**Comment by tiagov8** [comment]
test pass ✅
