### ISSUE TITLE
💄UI/UX - Move "View all" Videos to the bottom center

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#546]
CC @adamcogan @jaydenalchin @tiagov8 @BrookJeynes @bradystroud

Hi @JackDevAU 

Looking at https://github.com/SSWConsulting/SSW.People/issues/545 I thought we have room for improvement for the "View all" videos link.

- [x] 1. Change from "View All" to "View all"
- [x] 2. Change from "See More" to "See more"
- [x] 3. Move "View all" to be below the videos and center aligned (following the "See more" under Latest Rules)
- [x] 4. Make the link red 

From

<img width="1451" alt="Screenshot 2023-10-10 at 10 10 32 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/5acc9227-4b5d-4a1a-baec-e3bfea720f76">

To

<img width="1388" alt="Screenshot 2023-10-10 at 10 19 52 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/6b8dcb15-c3d0-4000-8d32-9ef6ecbe7072">

<img width="535" alt="Screenshot 2023-10-10 at 10 17 32 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/3d82761c-7295-4e89-9d34-09ba16f413d2">

**Comment by JackDevAU** [comment]
Hey @tiagov8 

1. Please "test please" 
https://staging.ssw.com.au/people/jake-bayliss/

**Comment by tiagov8** [comment]
> 1. Please "test please"

Test pass for "View all" but still missing some things...

- [ ] 1. Please complete the missing task (from "See More" to "See more")
- [ ] 2. I noticed the "Latest Rules" widget is missing from viewport 768px to 1024px. I have no idea why... but can you make it show?

**Comment by JackDevAU** [comment]
Hey @tiagov8 

>1. Please complete the missing task (from "See More" to "See more")

Not done - need to update the Widget 

>2. I noticed the "Latest Rules" widget is missing from viewport 768px to 1024px. I have no idea why... but can you make it show?

Done - fixed this responsive issue :O Good spot!

**Comment by JackDevAU** [comment]
Hey @tiagov8 

>1. Please complete the missing task (from "See More" to "See more")

Done - widget has been updated!

1. Please "test please"
[staging.ssw.com.au/people/jake-bayliss](https://staging.ssw.com.au/people/jake-bayliss/)

**Comment by tiagov8** [comment]
> 1. Please "test please"

test pass ✅
