### ISSUE TITLE
💄UI - Move language selector to be aligned with the logo on mobile

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#548]
@jaydenalchin 

Hi @JackDevAU 

- [x] 1. Please make the language selector be aligned to the logo on mobile view

You can do that by removing the below CSS:

```
@media screen and (max-width: 600px)
header>div.flex {
    flex-direction: column;
}
```

From

<img width="560" alt="Screenshot 2023-10-10 at 10 41 52 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/be345849-0af4-4d89-a264-2c3711fb49f4">

To

<img width="1162" alt="Screenshot 2023-10-10 at 10 42 29 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/d23c2437-3dd1-4e79-899e-f44462787883">

**Comment by JackDevAU** [comment]
Hey @tiagov8 

1. Please "test please" 
https://staging.ssw.com.au/people/jake-bayliss/

**Comment by tiagov8** [comment]
> 1. Please "test please"

Test pass ✅
