### ISSUE TITLE
🐛 BUG - Copy person’s information button

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#550]
cc @jaydenalchin 

Hey @JackDevAU 

The new feature is is broken in Chrome (Mac):

- [x] 1. Please investigate and fix

<img width="359" alt="Screenshot 2023-10-12 at 2 15 39 PM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/48e064c8-2428-4c76-8a04-60a3dda53af7">

**Comment by JackDevAU** [comment]
Hey @tiagov8 

1. Please "test please" 
https://staging.ssw.com.au/people/jake-bayliss/

**Comment by tiagov8** [comment]
Hi @JackDevAU 

❌ Test fail. Althought the positioning has improved there is a problem with the bg

I suggest something like:

<img width="435" alt="Screenshot 2023-10-19 at 11 45 31 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/a98875ef-c2f2-43b4-9d4c-801aaa80c1f7">

- [ ] 1. Please implement
- [ ] 2. Do you think it's a good idea to add tooltips on hover for these buttons? ("Copy details" and "Download image")

---

Tip: CSS for the rounded BG:

```
    background: #ffffff;
    border-radius: 50%;
    width: 25px;
    height: 25px;
```

**Comment by JackDevAU** [comment]
Hey @tiagov8 

> 1. Please implement
> 3. Do you think it's a good idea to add tooltips on hover for these buttons? ("Copy details" and "Download image")

Done - I've added a background to the buttons + added tooltips 

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/54c3b82a-2e5d-42dd-bfcd-baaf58f3eba3)
**Figure: Copy tooltip**

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/986c2165-498e-41ae-b0dd-8d4776b52af3)
**Figure: Download tooltip**

>2. I noticed that 1 of these is a <button> and the other a <a>... I expected them to be semantically consistent, which makes it easy for styling. I also expected a div around them... Can you fix?

Not done - The `<a>` tag is used to download whereas the `<button>` is used to copy. I feel it would be wasted effort to change the implementation to make them the same. If I change the button to an `<a>` tag i get the following: [jsx-a11y/anchor-is-valid](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/fffb05b38c8eee926ee758e9ceb9eae4e697fbdd/docs/rules/anchor-is-valid.md#jsx-a11yanchor-is-valid) and changing them to both buttons would require effort to get the download button working again.

**Comment by tiagov8** [comment]
Thanks @JackDevAU 

Looking good, but I think there is too much text in the tooltips.

I would use:

- Download photo
- Copy details

**Comment by tiagov8** [comment]
Also, can you try making the buttons have the exact same distance to the photo edge on the left and on the bottom. Currently there is way more space on the left than on the bottom

<img width="283" alt="Screenshot 2023-10-19 at 7 46 39 PM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/0ff64f21-9810-41f6-80c7-87df1a2759a4">

**Comment by jaydenalchin** [comment]
> Looking good, but I think there is too much text in the tooltips.
> 
> I would use:
> 
> * Download photo
> * Copy details

I would simplify further to just "Download" and "Copy"

**Comment by JackDevAU** [comment]
Hey @tiagov8

I've implemented the above changes

1. Please "test please"
[staging.ssw.com.au/people/jake-bayliss](https://staging.ssw.com.au/people/jake-bayliss/)

**Comment by tiagov8** [comment]
Hi @JackDevAU 

Sorry to make you revert that, but I want to override @jaydenalchin suggestion. 

It's good to have less words, but in this case I prefer to make this action more clear. "Download" may mean the page, not the photo... "Copy" may mean the photo, not the details.

- [ ] 1. Please revert to "Download photo" and "Copy details"

**Comment by JackDevAU** [comment]
Hey @tiagov8

I've reverted back to those! 

1. Please "test please"
[staging.ssw.com.au/people/jake-bayliss](https://staging.ssw.com.au/people/jake-bayliss/)
