### ISSUE TITLE
🙈 Toby Goodman profile not found! 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#554]
cc @adamcogan @pierssinclairssw 

Hi @JackDevAU 

@jontygardner has found a rule page (doesn't remember which one) with a link to https://www.ssw.com.au/people/toby-goodman

It gives a 404.

Looking at https://www.ssw.com.au/people/alumni/ I can't find Toby Goodman.

I assume his profile existed at some point... 

- [ ] 1. Did we lose this profile? Can you find out what happened with the page?

**Comment by JackDevAU** [comment]
Hi @tiagov8 

Just an update to this, I had a look at CRM and there are 2 "Toby Goodman" Users. 

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/9d481697-1bc9-4593-b3af-c4ffe1475668)
**Figure: Toby Users from CRM**

Hi @zl24622 

From People - we have 1 Toby Goodman with an ID of `b2ca522b-04a2-ea11-a812-000d3a79964c` but in CRM we have 2!?

1. How did we get 2? 
2. Are they different people? or the same?
3. Can we safely remove one?

**Comment by JackDevAU** [comment]
An Update: 

As per my conversation with Lu, we can't remove them from CRM. 
But I did have a look into the git history and found that his ID was changed. I have changed it back and now his profile is building on staging!
https://staging.ssw.com.au/people/alumni/toby-goodman/

**Comment by JackDevAU** [comment]
Done - https://www.ssw.com.au/people/alumni/toby-goodman/
His profile now exists again!

**Comment by tiagov8** [comment]
Hi @JackDevAU 

> As per my conversation with Lu, we can't remove them from CRM.

Do we have a reason for that?
I don't see a good reason to keep 2 entries for 1 person.

**Comment by JackDevAU** [comment]
Hey @tiagov8, 

As per a chat with Mehmet and Warwick. It is possible just not advisable. They have said not to due to the following, 

- Any records assigned to that Toby will have orphaned lookups
- the records are generated from Active Directory (i.e. there is probably a dupe there)
