### ISSUE TITLE
💄 UI - Add padding to iPad view

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#558]
Hi @JackDevAU 

The viewport from 768 to 1024 has no padding on the sides:

- [x] 1. Please fix

<img width="1384" alt="Screenshot 2023-10-20 at 9 41 42 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/d758fd0c-1f53-41b8-a904-1ddc9ef7e7eb">

**Figure: Add `mx-4` class to this div**

Cheers

**Comment by JackDevAU** [comment]
Hey @tiagov8

Done!  

1. Please "test please"
[staging.ssw.com.au/people/jake-bayliss](https://staging.ssw.com.au/people/jake-bayliss/)

**Comment by tiagov8** [comment]
@JackDevAU 

Test pass ✅
