### ISSUE TITLE
♻️ Add link to the phone number under CTA

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#559]
@tombui99 @camillars 

Hi team, 

We need to follow https://www.ssw.com.au/rules/do-you-know-to-hyperlink-your-phone-numbers on SSW.People CTA

<img width="1115" alt="Screenshot 2023-10-20 at 3 47 53 PM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/084dda72-268f-48f3-9919-93cf231f4da6">

### Tasks

- [ ]  1. Add link to phone number under the CTA

Thanks!

Caught by CodeAuditor: https://codeauditor.com/htmlhint/37988843-5f19-43b6-4676-fce9ace5d5f8

Related to: https://github.com/SSWConsulting/SSW.Rules/issues/1139

**Comment by JackDevAU** [comment]
Done! - https://github.com/SSWConsulting/SSW.People/pull/570
