### ISSUE TITLE
🐛 BUG - Skills not being shown on SSW.People profile unless they are linked to Consulting pages

### ISSUE THREAD

**Issue by synnoveisabel** [SSWConsulting/SSW.People#571]
cc: @JackDevAU @adamcogan @tiagov8 @BrookJeynes @bradystroud 

Skills in CRM that are not linked to Consulting pages are not shown on the SSW People Profile, see images below. As per my conversation with @tiagov8 all skills should be shown on the profile regardless of link to Consulting page.

![image](https://github.com/SSWConsulting/SSW.People/assets/36569610/a0c87386-16bd-4dc6-a90e-dde20a70bd6e)
**Figure: Skills on the SSW People Profile**

![image](https://github.com/SSWConsulting/SSW.People/assets/36569610/32950e90-a90c-40bd-9bb8-4c893e5bbcb8)
![image](https://github.com/SSWConsulting/SSW.People/assets/36569610/daf5e4e1-1eb7-4f79-abff-d5bcb4574bdb)
**Figures: Skills in CRM. The highlighted skills Python, OpenAI, Entity Framework Core, and Java are not shown on the profile**

**Comment by JackDevAU** [comment]
Done - Skills now show again even if they don't have a marketing page.
