### ISSUE TITLE
🐛 BUG - Not Showing All CRM Skills on People Profiles

### ISSUE THREAD

**Issue by Aibono1225** [SSWConsulting/SSW.People#583]
Cc: @adamcogan @bradystroud @JackDevAU  @william-liebenberg @calumjs @UlyssesMaclaren

Hi,

### Describe the Bug
Currently, our profile page doesn't display all the technical skills added to CRM.
Based on my investigation, this happens because we filter out the skills that lack a marketing link on the website

### Expected Behavior
Display all the skills on People Profiles

### Tasks
- [ ] Investigate
- [ ] Fix

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/69fb7feb-2abd-4855-9352-2a10d70f62a6)
**Figure: Missing AI and other language skills on this page **

**Comment by JackDevAU** [comment]
Hey Team, 

Done - this has now been reverted to show skills that don't have a marketing page. This seems to be a hot topic... Let's setup a meeting when people are back from holidays to discuss this further!
