### ISSUE TITLE
🐛 Skills | Archived skills being displayed on People pages

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.People#585]
Employee skills that come from CRM do not discriminate between active and archived skills.

![image](https://github.com/SSWConsulting/SSW.People/assets/100659715/47f9c333-01f2-4388-b161-fe93773c6fd5)
**Figure: zz.NET Core being displayed**

![image](https://github.com/SSWConsulting/SSW.People/assets/100659715/1fc10448-bc72-42cf-bc12-c092d07ccde4)
**Figure: "zz.NET Core" does not show up in CRM**

**Comment by Aibono1225** [comment]
As per my conversation with @zl24622 , we can use the attribute `statecode` to differentiate between active and inactive skills (0=active, 1=inactive)

this [PR](https://github.com/SSWConsulting/SSW.People/pull/586) should fix it

**Comment by Aibono1225** [comment]
Done - the page now only displays active skills:
![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/140ba159-693c-4af3-9aef-03cd18b72090)
