### ISSUE TITLE
♻️Megamenu - Add The New Menu

### ISSUE THREAD

**Issue by jeoffreyfischer** [SSWConsulting/SSW.People#594]
Cc:

Hi @Harry-Ross 

### Pain
Currently the [SSW People](https://www.ssw.com.au/people/) page still uses an in-built component for the MegaMenu.
However, in https://github.com/SSWConsulting/SSW.Website/issues/1560, a separate Megamenu project has been created so that can it be exported as a package to be used on SSW People. 
Link to Megamenu project: https://github.com/SSWConsulting/SSW.MegaMenu

### Tasks
```[tasklist]
### Tasks
- [ ] Add v4.0.0 of the megamenu to SSW People once it has been published to NPM
```

### Screenshots

![image](https://github.com/SSWConsulting/SSW.Website/assets/106663901/63b8a576-17fe-4020-b258-567cfee9bbda)
**Figure: The current in-built Megamenu on the SSW People page**

Thanks!

**Comment by BrookJeynes** [comment]
People is now using the latest design of the MegaMenu

ssw.com.au/people
