### ISSUE TITLE
💄JotForm - Book a Free Initial Meeting Popup

### ISSUE THREAD

**Issue by amankumarrr** [SSWConsulting/SSW.People#611]
The current width of the form with the popup is too wide, resulting in an extra vertical line under the close button. We should align the width with what we have on the SSW.Website.

![Booking-Form-on-People](https://github.com/SSWConsulting/SSW.People/assets/71385247/a756d3e2-9551-4688-b7ee-91cfac7e280e)

**Figure: Book a Free Initial Meeting with additional vertical line**

**Comment by BrookJeynes** [comment]
Done - 
<img width="750" alt="Screenshot 2024-02-23 at 08 32 49" src="https://github.com/SSWConsulting/SSW.People/assets/25432120/1e32e236-a632-4434-adbe-b30542457127">
