### ISSUE TITLE
🐛 Link styling missing

### ISSUE THREAD

**Issue by bettybondoc** [SSWConsulting/SSW.People#616]
cc @adamcogan @tiagov8 @matt-goldman 

Hi team,

The underline is missing in our links at SSW People. See https://www.ssw.com.au/people/adam-cogan/

- [x] 1. Please investigate and fix the link styling issue

![image](https://github.com/SSWConsulting/SSW.People/assets/33026270/e34b43ca-5953-4dfd-8e8b-f3900c125dbb)
**Figure: All the text inside the red boxes are actual links but don't look clickable**

![image](https://github.com/SSWConsulting/SSW.People/assets/33026270/771ff192-db02-48b1-8a6b-834d950235ef)
**Figure: Similar link issue found on the index page - https://www.ssw.com.au/people/**

As per email chain **Re: SSW People - missing link**

**Comment by Aibono1225** [comment]
Done ⭐

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/f3a1fed2-22cb-4eb7-b845-b2433fc6fc9a)
