### ISSUE TITLE
GitHub Contribuitions - Can we avoid horizontal scrolling?

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#640]
cc @GabbyWard @adamcogan 

Hi team, 

Looking at https://www.ssw.com.au/people/gabby-ward/ I couldn't see any greens at first...

Only later I noticed I needed to scroll horizontally to see the most recent months...

- [ ] 1. Can we avoid the scrolling?
        If not... could we make it load showing the most recent area (aka be auto scrolled to the latest weeks on the right end?)

![Image](https://github.com/SSWConsulting/SSW.People/assets/12601228/c999dcad-b7f7-4d8b-a254-f1ecea42590f)

![Image](https://github.com/SSWConsulting/SSW.People/assets/12601228/9691de5f-1e82-467f-b382-0210c5480d45)

**Comment by tiagov8** [comment]
cc @Tanya-Leahy @leahy268 @joshbermanssw @bradystroud @wicksipedia @JackDevAU 

--

**Note:** Same problem also reported by @adamcogan on email thread: **Re: SSW People - GitHub Contributions only show green when you scroll to the right**

> Hi Tiago
[Tanya Leahy | SSW.People | Australia's Leading .NET and Azure Consultants](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ssw.com.au%2Fpeople%2Ftanya-leahy%2F&data=05%7C02%7CTiagoAraujo%40ssw.com.au%7Cf196da77e6ec495505aa08dc9a4db681%7Cac2f7c34b93548e9abdc11e5d4fcb2b0%7C0%7C0%7C638554905771030956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=piniI%2B%2FnYdYaf%2B27tdlXyQaNz5MrqJKhEy5nx3F8kH8%3D&reserved=0)
 
> On SSW People we have GitHub Contributions widget:

> 1.	It only shows green squares when you scroll to the right. Can you repro?
> 2.	What control are we using?
> 3.	Are you happy with it?
> 4.	Can we ask the developer to change the default to fully see to the right?

> ![Image](https://github.com/SSWConsulting/SSW.People/assets/12601228/07337f99-e73c-4f62-a1e3-10b15fc4ae7d)

**Comment by bradystroud** [comment]
cc @GabbyWard @adamcogan @tiagov8 

## ✅ Done

I've made it a bit smaller so it fits on desktop screens

See PR #684 

![Image](https://github.com/user-attachments/assets/6fe71d81-92a6-4eb7-bada-e5a881c12116)
**Figure: ❌ Old - scrolling is annoying**

![Image](https://github.com/user-attachments/assets/452486be-ac68-4866-8582-4ab6a9b8e0a6)
**Figure: ✅ new - nice, but a bit smaller**
