### ISSUE TITLE
⛓️‍💥 Broken links - Alumni profiles not getting redirections

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#669]
On this rule https://www.ssw.com.au/rules/use-system-prompt/

Author is **Jack Reimers**. Clicking on his photo gives a 404: https://www.ssw.com.au/people/jack-reimers

The correct link is https://www.ssw.com.au/people/alumni/jack-reimers/ 

- [ ] 1. Make sure that every profile that changes from "current" to "alumni" gets a redirect to the working link

![Image](https://github.com/user-attachments/assets/7acb6049-9768-4eb5-9b50-a09db3fe60ef)

**Comment by tiagov8** [comment]
FYI - The example given has been fixed by @fenix2222 https://github.com/SSWConsulting/SSW.Rules.Content/pull/9122

**Comment by bradystroud** [comment]
cc @tiagov8 
## ✅ Done

Old URL now direct to alumni URLs
https://www.ssw.com.au/people/jack-reimers/
