### ISSUE TITLE
🐛 BUG - SSW People - showing rules that were not updated by Ari

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.People#671]
CC @adamcogan @bradystroud

**Hi Team,**

### Description

Update: This seems to be happening to all latest rules on SSW People. https://www.ssw.com.au/people/

Ari Grynberg's profile on SSW.People is currently showing rules that were not updated by Ari. This issue needs to be addressed to ensure that only the rules Ari has updated are displayed on his profile.

### Acceptance Criteria

- [x] Ensure that only the rules updated by Ari Grynberg are displayed on his SSW.People profile.
- [x] Verify that no unrelated rules appear on his profile.
- [x] Test the fix on staging before deploying to production.

**Comment by babakamyljanovssw** [comment]
cc: @bradystroud @JackDevAU 

Update:

PR: https://github.com/SSWConsulting/SSW.People/pull/674 addressed to update the widget props to match with latest version of package. It has fixed issue for users to shows only their updated rules on https://www.ssw.com.au/people.

However, the Azure Function data source is out of sync and it will be resolved by below:
Issue: https://github.com/SSWConsulting/SSW.Rules/issues/1438

So this issue can be closed as done.
