### ISSUE TITLE
🔗 Hide links from alumni

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#683]
cc @adamcogan @bradystroud @calumjs @christianmorfordwaitessw 

## Hi team,

I've been trying to fix old links from SSW.People and some of them are on the link section (e.g. ex-employees' blogs)

as per @ozdemir-mehmet 

> More importantly of ex SSW staff should we even be showing ANY links. The idea should be to promote our current staff not ex staff, right? So i'd say, keep there basic bio info, but don't provide any external links ex-staff. That's fixes the problem and makes sure that the emphasis is on current staff members.

- [x] 1. Can we disable the links section from all /alumni

![Image](https://github.com/user-attachments/assets/7871829b-3dea-4545-a070-b2b9e34eb131)

**Comment by bradystroud** [comment]
cc @ozdemir-mehmet @adamcogan @calumjs @christianmorfordwaitessw
Hey @tiagov8 

##  ✅ Done

I've disabled that section on all Alumni profiles.

https://www.ssw.com.au/people/alumni/gabriel-george/
![Image](https://github.com/user-attachments/assets/675b966f-6f89-47cf-a3fc-e8ea82c34fd1)
**Figure: Links section hidden**


Relevant PRs
#684 
#685
