### ISSUE TITLE
SSW.People website - Change the order of Designers

### ISSUE THREAD

**Issue by Pravino24** [SSWConsulting/SSW.People#690]
cc @jeoffreyfischer @bradystroud @wicksipedia 

Hi Team,

I was talking to @tiagov8 and we agreed to move my profile to the end (Because I am the only Graphic Designer)

- [ ] 1. Please change the order
![Image](https://github.com/user-attachments/assets/202a3cbb-0e57-450d-8d48-b0b25909b88a)

**Comment by tiagov8** [comment]
- [ ] 1. Do we have any documention on how to change employee's order? If not, please create one ;)

**Comment by wicksipedia** [comment]
order cannot be manually modified - from memory it is determined by billable rate, then title

**Comment by tiagov8** [comment]
> order cannot be manually modified - from memory it is determined by billable rate, then title

From user's perspective I think it would make more sense to sort by title first, then billable rate.

Could we modify that?

**Comment by wicksipedia** [comment]
> From user's perspective I think it would make more sense to sort by title first, then billable rate.

We’re sorting by billable rate so that the most senior people are at the top - this isn’t necessarily determinable via the title.

> Also, looking at SSW.People as a product, the feature to sort manually should be standard

I’m not sure if this adds much value but add it if you want

**Comment by tiagov8** [comment]
Replaced by https://github.com/SSWConsulting/SSW.People/issues/691
