### ISSUE TITLE
♻️ SSW.People - Change web content font to "Inter" font family

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#697]
cc @adamcogan @bettybondoc @jaydenalchin @hveraus 

### Pain  
 
As per [💄 SSW.Design - Change official webfont from Open Sans to Inter](https://ssw.visualstudio.com/SSW.Design/_workitems/edit/97260)

### Tasks

- [x] 1. CSS - Please update the web content font from **Open Sans** to **[Inter](https://fonts.google.com/specimen/Inter)**

**Note:** All sizes and variations should remain the same

Thanks!

---

Related Issues:
- SSW.Rules -  https://github.com/SSWConsulting/SSW.Rules/issues/1600
- SSW.Website - https://github.com/SSWConsulting/SSW.Website/issues/3269

**Comment by tiagov8** [comment]
Hey @BrookJeynes 

Can you prioritize this one?

Get help from @babakamyljanovssw and @JackDevAU if stuck. They just actioned the same task for SSW.Rules

**Comment by brookjeynes-ssw** [comment]
Done - "Inter" is now on prod for SSW People

![Image](https://github.com/user-attachments/assets/c4212bca-1ea1-4453-82d2-b5cbae006940)

**Comment by tiagov8** [comment]
Hey @bradystroud 

Please keep an eye on https://github.com/SSWConsulting/SSW.Rules/issues/1600#issuecomment-2456259948 because I believe SSW.People might have the very same Issue

**Comment by tiagov8** [comment]
Hey @bradystroud 

- [ ] 1. Please action the same as https://github.com/SSWConsulting/SSW.Rules/pull/1623 on SSW.People

**Comment by babakamyljanovssw** [comment]
Hey @tiagov8 

> 1. Please action the same as https://github.com/SSWConsulting/SSW.Rules/pull/1623 on SSW.People

✅ Done, drafted PR - https://github.com/SSWConsulting/SSW.People/pull/700
