### ISSUE TITLE
🐛 Bug - Job title is not consistent on SSW People with CRM

### ISSUE THREAD

**Issue by babakamyljanovssw** [SSWConsulting/SSW.People#709]
cc: @Ben0189 

On CRM Ben's job title is "Software Engineer I", but on SSW People it shows "Software Developer".

- [ ] Investigate and check if it is the same for all users
- [ ] Fix

# Acceptance Criteria
- Job title is consistent on SSW People with CRM for all users

# Screenshots
![Image](https://github.com/user-attachments/assets/9d0d169d-88b2-47e5-939e-f15aec9d2076)
**Figure: SSW People shows that Ben is Software Developer**

![Image](https://github.com/user-attachments/assets/99b39588-0d6e-41bc-8dda-e048dcaa0f97)
**Figure: CRM shows that Ben is Software Engineer I**

**Comment by Ben0189** [comment]
Duplicate from yak shaver - https://github.com/SSWConsulting/SSW.People/issues/710
